### ISSUE TITLE
Web Nova Plus

### ISSUE THREAD

**Issue by Jenikcz** [ibv/YTD#1]
Proběhl redesign stránek Nova Plus a tím nejde stahovat videa z webu

**Comment by ibv** [comment]
A používáte poslední verzi ytd-defs.xml?
Na webu je nová verze z minulého týdne 1.59.20180816.0.
Aktualizaci provést v dialogu About (poslední ikona v řadě), potom kliknout na číslo 1.59.20180816.0,
vystoupit a nastoupit do programu YTD a mělo by to jít.
