### ISSUE TITLE
youtube - "nepodařilo se najít adresu média. (EDownloadThreadError)

### ISSUE THREAD

**Issue by Peca006** [ibv/YTD#10]
Konkrétně třeba video [https://youtu.be/MhSgbp6niys](https://youtu.be/MhSgbp6niys), ale není jediné. Nejde mi to ani v Download station (Synology), kde jsem doposud běžně z YT stahoval. Možná je nějaká změna na YT, ale nenašel (google) jsem o tom ani zmínku...

**Comment by ibv** [comment]
Zatím jsem ve stavu teoretického hledání řešení, část programu, která zpracovává youtube.com se bude asi muset celá předělat.

**Comment by ibv** [comment]
Opraveno ve verzi [1.61](https://github.com/ibv/YTD/releases/tag/v1.61)

**Comment by JarekParal** [comment]
Zdravím, narazil jsem na stejný problém. Ještě cca. 2 měsíce zpět mi stahování na YouTube fungovalo, ale teď dostávám error: `Variable "Format List" not found (EDownloadThreadError)`.
Konkrétně jsem to testoval na [tomto videu](https://www.youtube.com/watch?v=-XIQKxA0cNk&list=PLeGkR0Itekq2gsYtst45AghHWe2-poX4Y&index=2&t=0s). 
![image](https://user-images.githubusercontent.com/6726556/72921772-2ffadd00-3d4c-11ea-9b16-abf74bf53829.png)

Šlo by se na to podívat? Případně mohu nějak pomoct s opravením chyby? Pracuji v práci s C++ Builder.

**Comment by ibv** [comment]
Kouknu na to, u yt.com asi něco změnili,
bude potřeba předělat parsování výstupu z yt.com, ty klíčová slova co vracel dříve už tam nejsou.

**Comment by pezalars** [comment]
Nová chybička u YouTube:
Proměnná "Format List" nebyla nalezena. (EDownloadThreadError)

**Comment by ibv** [comment]
Opraveno v dnešní verzi [1.64](https://github.com/ibv/YTD/releases/tag/v1.64)

**Comment by pezalars** [comment]
Možná, že jsem tupec a udělal nějakou chybu v instalaci... Ale tohle jsem tedy fakt nestáhl 
https://www.youtube.com/watch?v=QG2ls7gZW4o
![Výstřižek](https://user-images.githubusercontent.com/60270573/75284379-f3237980-5814-11ea-82fd-cb7aed696a5f.PNG)
