### ISSUE TITLE
Aktualizace 1.63 - problemove stahovani

### ISSUE THREAD

**Issue by Jenikcz** [ibv/YTD#15]
Provedl jsem aktualizaci na verzi 1.63, po zadání stahování z webů https://novaplus.nova.cz/ a http://videoarchiv.markiza.sk/ je stahování pomalé a pak vždy spadne s hláškou Chyba "Stahovani tohoto obsahu neni podporovano (EDownloadThreadError). Provedl jsem návrat k předešlé verzi 1.62 a vše funguje perfektně.
Děkuji.

**Comment by juwala63** [comment]
Potvrzuji, to samé jako uživatel Jenikcz.... Verze 1.63 se evidentně nepovedla....
Přílišné zaměření na jeden problém poškodilo vše ostatní co doposud fungovalo bez problémů.....
-----------------------------------------------------------------------------------------------------------------------------------
I confirm, the same as user Jenikcz .... Version 1.63 obviously failed ....
Excessive focus on one problem has damaged everything else that worked so far without problems .....

**Comment by mrkev885** [comment]
Stahovani z cesketelevize s verzi 1.63 je taktez velmi pomale (1MB za cca 10s). Downgradoval jsem na verzi 1.59.3 a tam to jede v poradku.

**Comment by ibv** [comment]
Je to "záhada hlavolamu", změny ve zdrojovém kódu nejsou takového charakteru, aby způsobovaly toto chování binárky, stejný kód zkompilovaný a provozovaný pod linuxem běží normálně, taktéž pod WinXP
kód z Delphi 7 funguje normálně.
YTD 1.63 z příkazové řádky funguje taky ok, zkusím zapátrat proč najednou GUI verze takhle blbne.
Zatím používejte verzi 1.62.

**Comment by ibv** [comment]
Opraveno v dnešním (24.4.2019) vydání v1.63, řešením bylo oddělit GUI a CLI verze aplikace.
