### ISSUE TITLE
Youtube nejede

### ISSUE THREAD

**Issue by mtravnicek** [ibv/YTD#16]
Re #10 
Aktualne patrne doslo k nejakemu vetsimu updatu googlu - search a sluzeb kolem
Na Youtube porad neco meni a promazavaji chci si stahnout me oblibene veci, nez mi to smaznou :)
Adresu kdyztak poslu nejak tajne ^_^
Doufejme, ze to neni nejaka vetsi zmena co nejde rychle fixnout.
Jak to vidis dik

**Comment by mtravnicek** [comment]
Ok reseni se jmenuje 4K Downloader

**Comment by ibv** [comment]
Opraveno v dnešním commit 9fb85ba.
Aktualizovaná binárka je v releasu 6 [zde](https://github.com/ibv/YTD/releases/download/v1.63/ytd-1.63.7z)
