### ISSUE TITLE
Nova plus nejde

### ISSUE THREAD

**Issue by KohlMilan** [ibv/YTD#17]
Od dnes nejde stahovat z novaplusu, jestli se na to podívaš, díky.

**Comment by ibv** [comment]
Nějaké přesnější info o adrese odkazu?
Zkusil jsem pár odkazů a v Linuxu i ve Windows stahování funguje.

![ytd-2](https://user-images.githubusercontent.com/2648561/64229650-a8bae300-ceea-11e9-9e61-f34f5a102bfb.png)

**Comment by KohlMilan** [comment]
Dík jsi rychlý, večer mi to fakt nešlo...
