### ISSUE TITLE
Nova Plus

### ISSUE THREAD

**Issue by Jenikcz** [ibv/YTD#18]
Poslední videa v sekci https://novaplus.nova.cz/porad/ordinace-v-ruzove-zahrade-2/reprizy, asi 10 dílů po vložení odkazu hlásí "Chyba skriptu:Regulérní výraz nebyl splněn. <multi_regexp content="x" id="url" var_prefix="loop_">  </multi_regexp> (EScriptedDownloaderScrioptError). Starší a v jiných sekcích co jsem vkládal funguje. Prosím, můžete se nato podívat ?
Děkuji.

**Comment by ibv** [comment]
Opraveno ve skriptech verze 1.63.20191225.0,
aktualizovat obvyklým způsobem.
