### ISSUE TITLE
Czech TV partially does not work

### ISSUE THREAD

**Issue by MyloshB** [ibv/YTD#21]
Generally, YTD works OK with Czech TV videos.
But 4 monts ago, CT started with new format for some videos within iVysilani.
YTD can download these videos, but the files cannot be played in standard media plyers like WMP, VLC, MPC-HC etc.
For example, all parts in Linka 3rd series can be downloaded but not played.
See: 
https://www.ceskatelevize.cz/ivysilani/11687510498-linka/219542150060010
https://www.ceskatelevize.cz/ivysilani/11687510498-linka/219542150060009
https://www.ceskatelevize.cz/ivysilani/11687510498-linka/219542150060004
https://www.ceskatelevize.cz/ivysilani/11687510498-linka/219542150060003
https://www.ceskatelevize.cz/ivysilani/11687510498-linka/219542150060002
https://www.ceskatelevize.cz/ivysilani/11687510498-linka/219542150060001
Could you, please, look on this issue?
Regards, Mylosh B.
PS: Happy New Year and many thanks for YTD!

**Comment by ibv** [comment]
Hi,
I'm afraid there is no simple solution here,
there is DRM protection and it is not easy to decrypt the content,
maybe try some play downloaded video in the web browser which can DRM, 
I really do not know yet.

![drm-1](https://user-images.githubusercontent.com/2648561/71618019-1be51500-2bbe-11ea-8828-5a76575dc791.png)



Regards, ibv
