### ISSUE TITLE
ceskatelevize.cz/ivysilani - porady s informacni videosmyckou

### ISSUE THREAD

**Issue by malyhrnek** [ibv/YTD#22]
Od noveho roku zacali pridavat pred porad informacni videosmycku o typu poradu. Napriklad pro deti, nasili atd. Tyhle porady sice jde stahnout, ale je nejaka chyba v obrazu resp. obraz nejede. Ostatni porady, ktere toto info nemaji jdou stahnout normalne bez chyb.
u brutalni nikity se mi smycka stahla do samostatneho souboru a byla prehratelna ale navazujici film v druhem souboru prehratelny uz nebyl.
Treba tento link nejde:
[https://www.ceskatelevize.cz/ivysilani/10243167758-ovecka-shaun-ii/210381463770010-pod-jednou-strechou](url)
Tenhle link myslim bude funkcni 7dni ode dneska, ale delaji to myslim vsechny s porady pro deti.
Kdybys mel cas a chut se na to podivat ... Dekuji.

**Comment by ibv** [comment]
V tomto případě jde o chráněný obsah (DRM), momentálně se s tím nedá nic dělat,
možná až s něčím příjdou kluci od KODI a jejich pluginy ...

![drm-1](https://user-images.githubusercontent.com/2648561/71812094-9c03f280-3076-11ea-9d99-235d0d49b0d3.png)
