### ISSUE TITLE
Aktualizace 1.64 - nefunkční stahování

### ISSUE THREAD

**Issue by Jenikcz** [ibv/YTD#23]
Provedl jsem aktualizaci na verzi 1.64, po zadání stahování z webů https://novaplus.nova.cz/ a http://videoarchiv.markiza.sk/ stahování je nefunkční. Provedl jsem návrat k předešlé verzi 1.63 a stahování z těchto webů funguje.
Děkuji.

**Comment by ibv** [comment]
Tady je problém komplikovanější, změnil jsem trochu vnitřek programu, 
pracuji na nápravě, ale času málo ...

**Comment by ibv** [comment]
Opraveno v aktualizaci binárek z 5.3.2020,
https://github.com/ibv/YTD/releases/tag/v1.64
