### ISSUE TITLE
iPrima.cz, přímé zadání manifest souboru .mpd

### ISSUE THREAD

**Issue by ttkanicka** [ibv/YTD#24]
Dobrý den,nemůžu přijít kam se zadává,nebo jak se se souborem .mpd pracuje.Poradí někdo?Děkuji.

**Comment by ibv** [comment]
Postup pro FireFox, (pro Chrome je obdobný):
1. Založení účtu na iprima.cz a přihlášení se na stránky např. přes e-mail
2. V programu ytb povolit ve vlastnostech stahovaní u MPEG-DASH - "Enable download MPEG-DASH stream" a "Enable download MPEG-DASH audio stream"
![m-4](https://user-images.githubusercontent.com/2648561/75095130-34582700-5592-11ea-9637-9db978e08795.png)
3. Najít v prohlížeči stránku s filmem na iprima.cz/filmy , klávesa F12 (nástroje pro vývojáře)-Síť, do filtru zadat .mpd, hledaný manifest mpd je v URL požadavku, 
![m-2](https://user-images.githubusercontent.com/2648561/75095289-8c435d80-5593-11ea-9f37-4685f2ef793d.png)
4. Adresu mpd vzít do paměti CTRL+C a vložit do programu ytd přes ikonu a pustit stahování
![m-3](https://user-images.githubusercontent.com/2648561/75095122-22768400-5592-11ea-9e99-51fef279911d.png)
5. Po stažení spojit video a audio pomoci ffmpeg do jednoho kontejneru podle návodu zde https://github.com/ibv/YTD/issues/14

**Comment by ttkanicka** [comment]
Mám stejný problém jako kolega nademnou.Pořád dokola to stahuje knihovny.Váš návod na soubor  .mpd mě nefunguje.Hlásí mě to pořád chybu.Program mám ve firevolu povolený. 
![screen](https://user-images.githubusercontent.com/61106742/75096600-83598880-55a1-11ea-8348-05772c44ab6c.PNG)

**Comment by ibv** [comment]
Problém je ve verzích knihoven OpenSSL, pro 32bit verzi YTD jsou v release https://github.com/ibv/YTD/releases/tag/v1.64 nové odkazy.
YTD pro 64bit opravím později.
Jednoduchý test pro ověření fungování SSL je kliknout na ikonu About.
Pokud se objeví text nenalezeno, viz obr., tak jsou SSL knihovny nekomaptibilní.
![ytd-1](https://user-images.githubusercontent.com/2648561/75112209-ebf84200-5641-11ea-88f9-84dbab082fbb.png)

**Comment by ttkanicka** [comment]
Děkuji, tohle pomohlo.Vše funguje.Těším se na verzi x64.

**Comment by ibv** [comment]
Verze 1.64  v dnešní aktualizaci binárek (5.3.2020)
https://github.com/ibv/YTD/releases/tag/v1.64
