### ISSUE TITLE
YTD 1.64 (x64) installation problems

### ISSUE THREAD

**Issue by MyloshB** [ibv/YTD#25]
Hi IBV, 
I tried to use YTD version 1.64 (x64) in these steps:
- download ZIP-file with x64 version and unpack all into C:\Program Files\YTD folder,
- download 2 ZIP-files with OpenSSL x64 and unpack 4 recommended files into YTD folder,
- start YTD.EXE normally and also in mode "as administrator" (the results are the same),
- dialog box about RTMP is displayed => click Yes/Ano,
![obrazek](https://user-images.githubusercontent.com/58863827/75095077-b005a400-5591-11ea-979c-053b6ff8db96.png)
- dialog box about MSDL is displayed => click Yes/Ano,
![obrazek](https://user-images.githubusercontent.com/58863827/75095106-f824c680-5591-11ea-91a9-8293ff57c4c5.png)
- information about the success is displayed => restart YTD,
![obrazek](https://user-images.githubusercontent.com/58863827/75095120-1d193980-5592-11ea-9e4e-c6a41d71673d.png)
- after restart YTD is the same situation on the screen, the application calls missing RTMP and MSDL,
- YTD folder does not contain any RTMP and MSDL files in this moment :-/
- afterward I manually copied RTMP and MSDL files from the folder with old YTD x32 and start YTD x64, but all mentioned messages appeared again,
- currently my folder with YTD x64 contains these files:
![obrazek](https://user-images.githubusercontent.com/58863827/75095221-f7d8fb00-5592-11ea-9d5d-ddc9382beaea.png)
Did I forget to do any step in the installation?
Please, help :-)
FYI, YTD version 1.64 (x32) works OK on the same machine, fortunatelly...
Regards, MyloshB
PS: Problems with televisions STV and NOE I will report in new issue.

**Comment by ibv** [comment]
Hi,
try disabling the old protocols (rtmp, msdl) in the menu, do you know any pages that require these protocols?
basically, only the ssl protocol is required
![m-5](https://user-images.githubusercontent.com/2648561/75095631-3375c400-5597-11ea-829a-398db1132fc8.png)

**Comment by ibv** [comment]
The problem is in different versions of SSL, some of which depend on others,
in the download section there are new links for OpenSSL x64
