### ISSUE TITLE
Support for TV NOE and STV (RTVS) is missing

### ISSUE THREAD

**Issue by MyloshB** [ibv/YTD#26]
Hi IBV,
could you, please, add or improve support for TV Noe and Slovak TV (STV aka RTVS)?
For example TV Noe URLs:
- http://www.tvnoe.cz/porad/26669-mse-svata-z-kostela-nanebevzeti-panny-marie-slapanice
- http://www.tvnoe.cz/porad/26318-cvrlikani-vladimir-merta
For example Slovak TV URLs:
- https://www.rtvs.sk/televizia/archiv/14372
- https://www.rtvs.sk/televizia/program/14822
I am pretty sure, that downloading from www.rtvs.sk was OK in the far Pepak's past :-)
Thanks in advance, Mylosh B.

**Comment by ibv** [comment]
Fixed in scripts 1.64.20200301.0,
update by clicking the About icon then clicking the latest version of the script,
as indicated in the procedure here https://github.com/ibv/YTD/issues/5
