### ISSUE TITLE
64bit verze

### ISSUE THREAD

**Issue by Scipioxx** [ibv/YTD#27]
Nenačte knihovny msdl_dll.dll a rtmpdump_dll.dll (program hlásí, že nejsou instalovány) a 64 bitové verze jsem nikde na internetu nenašel. Určitě by se hodilo dát někam do popisu i odkaz na tyto knihovny, nejen na SSL... OS: Windows 10

**Comment by ibv** [comment]
Vzhledem k tomu, že podpora flashe a msdl v prohlížečích klesá, tak to nehodlám moc řešit.
V 32bit verzi ty protokoly fungují, v 64bit ne, nejsou dll.
V nastavení YTD se dají vypnout hlášky o nedostupnosti knihoven, program může fungovat i bez nich.
