### ISSUE TITLE
YTD v1.64 (21.02.2020) - aktulizace 5.3.2020

### ISSUE THREAD

**Issue by Jenikcz** [ibv/YTD#28]
Děkuji za úpravu, provedl jsem aktualizaci a vyzkoušel, nyní na webech např. https://novaplus.nova.cz/ a http://videoarchiv.markiza.sk/ stahování funguje, jenom před koncem se stahování zastaví a na příslušném řádku informuje "Stahuje se" a procenta průběhu se zastaví na různých hodnotách např. 77, 85, 94% a stahování se neukončí s hlášením "Dokončeno".
Dále se chci zeptat šlo by přidat stahování z webu Televize Seznam (segmentované video m4s) ?
Děkuji.

**Comment by ibv** [comment]
Info o dokončeném stahování se objeví po obnovení zobrazení seznamu stahovaní nebo po kliknutí na jiný řádek, bude to nějaká drobnost v programu, opravím v další aktualizaci.
Na TVseznam se kouknu příležitostně.

**Comment by ibv** [comment]
Opraveno ve verzi 1.65
