### ISSUE TITLE
Nelze stahovat z archivu CT

### ISSUE THREAD

**Issue by jirkaza** [ibv/YTD#29]
Dobrý den, bohužel (už opět?) nelze stahovat z archivu ČT. Pozoruju to poprvé dnes, ještě před nějakými dvěma týdny bylo vše OK. Mezitím jsem ale upgradoval verzi YTD (1.63 => 1.64), ale nevím, zda to má souvislost, protože návrat ke starší verzi jsem nezkoušel.

Projev: link z FF se v YTD zobrazí jako playlist a dále rozdělí na tři samostatné, proběhne takřka bleskové "stažení" prvního (ve skutečnosti se nestane nic) a u dalších se už nedaří vůbec nic... Viz screenshoty v příloze.

YTD běží pod Wine v Kubuntu 18.04LTS.

Děkuji za péči věnovanou problému....
![01_YTD_po_vlozeni_odkazu](https://user-images.githubusercontent.com/5891520/76444022-a1a5ed80-63c3-11ea-910c-233521bb5a4d.png)
![02_YTD_po_spusteni_odkazu](https://user-images.githubusercontent.com/5891520/76444025-a2d71a80-63c3-11ea-88c0-45d9b4bf677a.png)

**Comment by ibv** [comment]
Zdravím příznivce Linuxu :)
Řešení je jednoduché, použít binárku z aktualizace 5.3.2020, stáhnout znovu zkomprimovaný balíček, rozbalit a pustit, v hlavní liště programu YTD se musí objevit "(fpc)".

![ytd-3](https://user-images.githubusercontent.com/2648561/76492100-ae602b00-642f-11ea-9644-fa6ed85f4b3c.png)

Jinak YTD běží nativně i v Linuxu, provozuji v něm hlavní vývoj a pak to převádím do prostředí Windows, na GitHubu mám repo s verzí pro Linux, nejsou tam ovšem binárky, musí se provést kompilace v Lazarusu (fpc).

**Comment by jirkaza** [comment]
Tak jsem se zaradoval, ale předčasně... Poté, co jsem udělal změnu binárky (pouze té), tak dojde už při pokusu o vložení URL k chybě. Pakliže zvolím OK, nestane se nic (URL se nezkopíruje do programu). Viz opět screenshoty...
![03_YTD_verze](https://user-images.githubusercontent.com/5891520/76505755-43701d80-644a-11ea-9e1b-cfda85f38480.png)
![04_YTD_access_violation](https://user-images.githubusercontent.com/5891520/76505760-4408b400-644a-11ea-8f35-2272200dac19.png)

**Comment by ibv** [comment]
Kompilátor fpc na rozdíl od Delphi používá jiné knihovny pro regulární výrazy, v komprimovanem 7z balíčku je i patřičná (32,64bit) knihovna pro pcre. Takže nakopírovat i tuto knihovnu k ytd.exe.

**Comment by jirkaza** [comment]
Tak přidání pcre3.dll částečně pomohlo, ale objevil se jiný problém: YTD sice zdánlivě jede, ale v cílovém (ukládacím) adresáři se neukládá nic a stahování v YTD se "zakousne" kousek před koncem (viz opět screenshot).
Zvolil jsem jiné URL, aby soubor nebyl tak velký...
![05_YTD_zdanlive_bezi](https://user-images.githubusercontent.com/5891520/76508762-36a1f880-644f-11ea-950a-493be4eef612.png)
![06_YTD_nemuze_skoncit](https://user-images.githubusercontent.com/5891520/76508765-373a8f00-644f-11ea-82ba-da900566ea19.png)

**Comment by ibv** [comment]
Opraveno ve verzi 1.65

**Comment by jirkaza** [comment]
Děkuji mnohokrát, funguje.
