### ISSUE TITLE
Nefunguje download z YT a Novaplus

### ISSUE THREAD

**Issue by MACo-666** [ibv/YTD#30]
Ahoj, dnes jsem aktualizoval na verzi 1.64, ale bohužel mi nefunguje download z NovaPlus, i když ve verzi 1.63, kterou mam na jiném PC, to funguje.
Download z YouTube mi nefunguje ani v jedné verzi.

Díky za ochotu a pomoc.

![1 63](https://user-images.githubusercontent.com/62750263/77756292-2ed97b00-702f-11ea-9038-2b24af52b9d8.jpg)
![1 64](https://user-images.githubusercontent.com/62750263/77756294-300aa800-702f-11ea-9009-ebf6c98cf8fd.jpg)

**Comment by ibv** [comment]
V nové verzi 1.65 je funkce pro generování bugreport.txt, (třetí ikonka zprava),
obsah tohoto souboru přihoďte k popisu chyby .

**Comment by MACo-666** [comment]
Nainstaloval jsem si novou verzi. Bohužel stahování z NovaPlus ani YouTube stale nefunguje a piše stejné chyby jako verze 64. Při pokusu o vytvoření Bugreportu (pomocí tlačítka) mi vyskočí tato hláška a report se nevygeneruje.

![1 65](https://user-images.githubusercontent.com/62750263/78782458-5cfd7a00-79a2-11ea-84ed-9f434d73da7d.jpg)

**Comment by MACo-666** [comment]
Mimochodem, teď jsem zjistil, že při každém novém spuštění se ta 65ka tváří, jako že je pouštěná poprvé a ptá se na nastavení portable modu a kontrolu nových verzí. Chová se tak jak při nastavení klasické verze, tak i portable modu.

**Comment by ibv** [comment]
Novaplus opravena ve skriptech 1.65.20200408.0, aktualizovat z menu ikona About.

**Comment by MACo-666** [comment]
Bohužel nefunguje :-(
![image](https://user-images.githubusercontent.com/62750263/78940212-c6ba7880-7ab5-11ea-9367-275baeaa0946.png)

**Comment by ibv** [comment]
Hmm, tady asi nefunguji openssl knihovny, zkuste prosim jinou verzi 1.1 nebo 1.0 dle nápovědy na releasech, samozřejmě odpovídající 32 nebo 64 bit.

**Comment by MACo-666** [comment]
Po nahani openssl 1.1 se stav nezmenil, ale po pridani openssl 1.0 si program po nove spusteni sam rekl o aktualizaci. Download z NovaPlus i YT diky tomu uz FUNGUJE. Program se ale porad chova podivne - nepamatuje si ulozeni nastaveni - pri kazdem spusteni se tvari, jako ze je pousteny poprve a chce odklikat nastaveni a znovu stahnout definici skriptu. Take si nepamatuje adresar kam ukladat a diky tomu hazi chybu pri zapoceti prvniho downloadu. Pri mazani radku s URL obcas taky hodi chybu a spadne.

**Comment by ibv** [comment]
Ke stažení je opravený/aktualizovaný 32/64bit instalační soubor 
https://github.com/ibv/YTD/releases/tag/v1.65
