### ISSUE TITLE
Rozhlas.cz a nový MůjRozhlas.cz

### ISSUE THREAD

**Issue by ladabohac** [ibv/YTD#32]
U stahování nových audií z webu rozhlasu (např. `https://dvojka.rozhlas.cz/rako-za-uspechem-ceskych-dlazdic-stoji-velka-fyzicka-drina-zamestnancu-kteri-8161169` ), se soubor automaticky pojmenuje 

> c89cb67535e62347262df8e573c709d0.mp3

, což je nepraktické. Stahovací odkaz to použije: `https://dvojka.rozhlas.cz/sites/default/files/audios/c89cb67535e62347262df8e573c709d0.mp3?uuid=5e6fb268b93e7` . 

Pokud by se upravil na: `https://dvojka.rozhlas.cz/audio-download/sites/default/files/audios/c89cb67535e62347262df8e573c709d0` , tak už to má název lepší: 

> pribehy_slavnych_znacek-dvojka-2020-03-10-rako_za_uspechem_ceskych_dlazdic_stoji_velka_fyzicka_drina_zamestnancu_kteri_pracovali_polonazi-pribehy_slavnych_znacek_rako.mp3

 . Ale ideální by byl asi takto: 

> Příběhy slavných značek (2020-03-10_1830) Rako: Za úspěchem českých dlaždic stojí velká fyzická dřina zaměstnanců, kteří pracovali polonazí.mp3

Kdyby to šlo takto podobně udělat i u starších odkazů, které míří na `media.rozhlas.cz/_download/xxxxxxx.mp3` , bylo by to také moc fajn. 

Druhá věc je pokud by šlo stahovat z mujrozhlas.cz.  Např.: `https://www.mujrozhlas.cz/nepovinna-cetba/jana-plodkova-cte-fejeton-karla-capka-o-alelidech` si lze stáhnout v MP3 na `https://croaod.cz/download/44a19b4d-9652-453a-adf5-73ed24c7f605.mp3` . Tady ale bohužel není URL ve zdrojovém kódu stránky, ale lze zjistit při pozastavení puštěného audia v prohlížeči založeném na Chromiu přes funkci prozkoumat. 

Kdyby to šlo nějak zařídit/dodělat, byla by to paráda :-).

**Comment by ibv** [comment]
Opraveno ve verzi 1.65, mujrozhlas.cz zatím není.

**Comment by ibv** [comment]
Mujrozhlas.cz je v atualizaci skriptu 1.65.20200424.0,
aktualizovat podle navodu zde https://github.com/ibv/YTD/issues/5

**Comment by ladabohac** [comment]
Odstavili server media.rozhlas.cz - např.: pro https://prehravac.rozhlas.cz/audio/2891066 je nyní URL média https://croaod.cz/download/c7d27b9a-9050-37a8-b760-39587a64bc86.mp3 . http://media.rozhlas.cz/_download/2891066 již nefunguje. Taky je v nejnovější verzi neaktivní ikona přispět na další rozvoj.

**Comment by ibv** [comment]
Opraveno v atualizaci skriptu 1.65.20200721.0,
aktualizovat podle navodu zde #5
