### ISSUE TITLE
1.64 verzia sa nespusti

### ISSUE THREAD

**Issue by mpajer** [ibv/YTD#33]
1.63 funguje, ale 1.64 sa ani nespusti, iba vyskoci hlaska:
File not open.
Press OK to ignore and risk data corruption.
Press Abort to kill the program.

Z hlasky netusim kde moze byt problem a ziadne logy som v aplikacnom adresari nenasiel..
![Capture](https://user-images.githubusercontent.com/4747480/77921318-e4ab0080-729f-11ea-8cc3-371eaac3d25f.PNG)

**Comment by ibv** [comment]
Podobně se program chová pokud chybí nějaká dll knihovna. 
Povedlo se vyklopit celý obsah 7z balíčku na disk? Součástí je i knihovna pcre.dll, 
ověřte, jestli je v adresáři s ytd.exe.

**Comment by mpajer** [comment]
ano vsetko sa rozbalilo v poriadku. skusal som 32 aj 64bit, v 32bit je pcre3.dll a v 64bit je pcre64.dll.

**Comment by ibv** [comment]
zkusit zapnout portable mod v menu, případně přejmenovat ytd.xml a pustit ytd, vygeneruje se nový ytd.xml.

**Comment by mpajer** [comment]
Bohuzial kedze program sa vobec nespusti, nemam ako prepnut portable mod :)
Takisto nevygeneruje ani ytd.xml, je tam iba ytd-defs.xml.
Skusal som aj vsetky rezimy kompatibility aj spustenie ako administrator, zatial nic nepomohlo..
Neda sa nejakym prepinacom spustit debug mod kde by som v logu videl nejake blizsie info, co konkretne padlo?

**Comment by pezalars** [comment]
Potvrzuji chybičky. Například když zvolím setup.exe, tak se nestane vůbec nic. Teoreticky by to mělo spustit instalaci, ale nic se neděje. Ale já nejsem programátor, pouze chabý uživatel. ?ožná někde dělám chybu...
![Výstřižek](https://user-images.githubusercontent.com/60270573/78170421-35168f80-7453-11ea-8c3a-10e43bad8c2d.PNG)

**Comment by mpajer** [comment]
ten setup.exe nefunguje ani mne

**Comment by ibv** [comment]
Zkuste novou verzi 1.65, případně koukněte do prohlížeče událostí ve woknech, jestli tam není chybová hláška.

**Comment by mpajer** [comment]
Bohuzial stale rovnaka chyba, v event viewri som nic nenasiel

**Comment by ibv** [comment]
Zkuste u fungující verze 1.63 nechat vygenerovat v portable modu ytd.xml a ten nakopirovat k verzi 1.64+, jestli se objeví stejná chybová hláška.

**Comment by mpajer** [comment]
Ano stale rovnaka chybova hlaska :(

**Comment by ibv** [comment]
Můžete zkusit pustit ytd 1.64+ na jiném počítači ?

**Comment by cerdacz** [comment]
1.65 x64 se spusti, ale pri kazdem spusteni 
- hlasi chybejici knihovny - byt jsou vsechny nainstalovany
- vsechny presnosy jsou Failed (predpokladam dusledek nenalezenych knihoven)
(zkouseno smazani XML, portable mod ... ani jedno nepomohlo)

1.65 x32 bez problemu

**Comment by ibv** [comment]
Ke stažení je opravený/aktualizovaný 32/64bit instalační soubor 
https://github.com/ibv/YTD/releases/tag/v1.65

**Comment by cerdacz** [comment]
x64 verze instaluje win32 manifest ;)
`<?xml version="1.0" encoding="UTF-8" standalone="yes" ?>
<assembly xmlns="urn:schemas-microsoft-com:asm.v1" manifestVersion="1.0">
	<assemblyIdentity 
		version="1.0.0.0" 
		processorArchitecture="X86" 
		name="Pepak.YTD" 
		type="win32" />
	<description>http://www.pepak.net/ytd</description>
	<dependency>
		<dependentAssembly>
			<assemblyIdentity 
				type="win32" 
				name="Microsoft.Windows.Common-Controls" 
				version="6.0.0.0" 
				processorArchitecture="*" 
				publicKeyToken="6595b64144ccf1df" 
				language="*" />
		</dependentAssembly>
	</dependency>
</assembly>`

**Comment by ibv** [comment]
jj, to by mohl být problém, mrknu na to.
