### ISSUE TITLE
Nova Plus

### ISSUE THREAD

**Issue by Jenikcz** [ibv/YTD#34]
Dnes programátoři změnily na Nova Plus videopřehrávání videí. Po vložení odkazu hlásí "Nepodařilo se stáhnout stránku informací o médiu". (EDownloadThreadError) anebo po vložení odkazu se nic neděje a jenom hlásí "Připravuje se download". 
Prosím, můžete se nato podívat ?
Děkuji.

**Comment by ibv** [comment]
Novaplus opravena ve skriptech 1.65.20200408.0, aktualizovat z menu ikona About.

**Comment by Jenikcz** [comment]
Děkuji.
Na 1PC s W10 funguje, na 2PC s W7 nejde aktualizovat, hlasí v okně O aplikaci "Nejnovější verze: not found / not found. Nejde na Github zveřejnit celý program znovu s updatem skriptu ? Zkoušel jsem stáhnout z github/YTD/docs/ytd-defs.xml a nakopíroval do adresáře s YTD ale po otevření aplikace hlásí "Nesprávny uzavírací tag pro element link", takže program nefunguje.
Dále mám dotaz-již nebude verze programu v kontejneru 7z, bude jenom intalovatelná verze exe ?
Děkuji.

**Comment by MACo-666** [comment]
Mám stejný problém - nelze aktualizovat. Navíc, program se při každé puštění chová, jako by byl puštěný poprvé a chce nastavení.

![image](https://user-images.githubusercontent.com/62750263/78940364-008b7f00-7ab6-11ea-9bf6-023b293fea52.png)

**Comment by ibv** [comment]
Chyba v About not found (nenalezeno) znamená, že v programu nezafungovalo načtení knihoven pro https komunikaci (openssl).

Ten odkaz pro ytd-defs.xml by měl být správný, když ho zkusíte načít do FireFoxe, zobrazí se vizuálně správně, tzn. je čitelný?
Ano, do budouna by měl být hlavní formát distribuce klasický instalátor.

**Comment by Jenikcz** [comment]
Nejsem tak zdatný, "načtení knihoven pro https komunikaci (openssl)" openssl soubor jsem v adresářích a podadresářích YTD nikde nenašel. Prosím můžete mi nějak objanit jak na to ?
K posouzení správnosti načtení ytd-defs.xml do FireFoxe viz obrázek.
![ytd-defs firefox](https://user-images.githubusercontent.com/42541393/79009110-15701d00-7b5f-11ea-81ac-0919f36a5ee5.jpg)

**Comment by ibv** [comment]
Jestli vám funguje v některé předchozí verzi https stahování, tak si jenom ty openssl knihovny
překopírujte do adreáře s verzí 1.65 a mělo by to zafungovat.
Na W7 jsem program netestoval, pouze na W10.

**Comment by Jenikcz** [comment]
Tak jsem zkoušel různé možnosti na PC s W7 kopírování openssl knihoven OpenSSL 1.1 ze starších verzí, bez uspěchu. Až jsem nakopíroval openssl knihovny OpenSSL 1.0 a najednou funguje aktulizace skriptu na v. 1.65.20200408.0. Zajimavé že ve verzi 1.63 fungují knihovny 1.1 a ve verzi 1.65 knihovny 1.0 pro aktulizaci skriptu.

**Comment by ibv** [comment]
Ke stažení je opravený/aktualizovaný 64bit instalační soubor  
https://github.com/ibv/YTD/releases/download/v1.65/ytd-1.65_x64.exe
