### ISSUE TITLE
Moře chyb

### ISSUE THREAD

**Issue by trumpeta** [ibv/YTD#35]
Aplikace otravuje uživatele spoustou chyb, hned při startu se objeví dotazy na stažení chybějících knihoven RtmpDump a MSDL. Potvrzením sice program ohlásí že byly úspěšně staženy ale hned při dalším spuštění aplikace se tyto dotazy opakují znova. Varování se sice dají vypnout v nastavení ale potom člověk neví jestli aplikace s knihovnami pracuje nebo ne, v adresáři přítomny jsou.
Další bug je že to dokáže najít aktualizaci ale stáhnout a nainstalovat už ne, s nějakou chybou (verze 1.63). Takže aktualizovat jde jenom přes instalátor z githubu.
Další nefunkčnost je že videa z některých webů a není jich zrovna málo, které jsou oficiálně podporovány nejde stáhnout ale spadne to s nějakou chybovou hláškou.
Další věc je že nejde otevřít odkaz na github z About... 
Prostě to ve mě budí dojem odfláknutosti a jako že to snad autor vůbec ani netestoval.
Pepakovy buildy byly daleko použitelnější, weby které inzeroval skutečně fungovaly. Mám dokonce pocit že s každou novou verzí to funguje hůř a hůř, na takový vývoj bych se vyprdnul a věnoval čas něčemu perspektivnějšímu.

**Comment by ibv** [comment]
Ano rozumím Vám, máte pocit, že za své investice (nula)  nedostáváte odpovídající hodnotu, v tom případě Vám nemohu pomoci, snad jen doporučení zvolit alternativní náhradu.
