### ISSUE TITLE
YTD File not open

### ISSUE THREAD

**Issue by jannyba** [ibv/YTD#36]
Ahoj

pri starte 32 aj 64 bit verzie vidim tento error
![image](https://user-images.githubusercontent.com/56595831/80292835-ff1ab180-8759-11ea-84e4-f015f3eb766f.png)

Pustil som to cez process activity viewer
![image](https://user-images.githubusercontent.com/56595831/80292841-0f329100-875a-11ea-8e5b-d9f9f4e82501.png)

Odhadol by som to, ze v instalatore chyba nejaka .dll, napr z fpc. alebo lazarus.
Kazdopadne poprosim doplnit aby sa .dll kontrolovali pred nacitanim a ak niektore chyba vypisala sa korektna error hlaska.

**Comment by ibv** [comment]
Na jakém OS k tomu dochází? Win10 nebo jiný?
V instalátoru by měly být všechny součásti, zkuste ještě pustit ytd s vyššími právy (jako správce),
případně odmazat/přejmenovat soubor ytd.exe.manifest.
Na obrázku jsou všechny soubory nutné pro běh ytd 64bit.

![ytd-4](https://user-images.githubusercontent.com/2648561/80362192-819e9080-8882-11ea-9f82-6304b06630bd.png)

**Comment by jannyba** [comment]
Dobry vecerm

po odstraneni ytd.exe.manifest sa zmenilo len to, ze v error okne su graficke ikonky:

![image](https://user-images.githubusercontent.com/56595831/80635005-95e9b580-8a5b-11ea-86e8-5afb9cac347d.png)

Skusal som odstranit aj ytd-defs.xml aj ho vratit a skopirovat na ytd.xml

Je to Windows 7 x64 s najnovsou aktualizaciou 04/2020. Je mozne teda lepsie osetrit otvaranie suborov, alebo zapnut cez parameter debug rezim?
dik

**Comment by ibv** [comment]
Zkuste stáhnout znovu instalační soubor ytd-1.65(32/64), případně verzi pro XP, 
nainstalovat a pustit v debugeru [https://www.nirsoft.net/utils/simple_program_debugger.html](https://www.nirsoft.net/utils/simple_program_debugger.html). 
Na Win7 už nemám možnost testovat, v souboru ytd-defs.xml jsou definice skriptu, v ytd.xml je konfigurace ytd, nezaměňovat tyto soubory.

**Comment by jannyba** [comment]
Dobry den

sorry za zdrzanie, uz sa tomuto venujem. Spustanie ako administrator nema vplyv na chybu. Debug log v prilohe. dik.

[Debug Events List.txt](https://github.com/ibv/YTD/files/4770311/Debug.Events.List.txt)
