### ISSUE TITLE
Problém s instalací

### ISSUE THREAD

**Issue by Warpik13** [ibv/YTD#37]
Dobrá práce, která má bohužel mouchy, umí konečně seznam/stream - bohužel nepoužitelná. Verze 1.65 se nainstaluje, nemá ikonu (to by nevadilo). Co je hlavní problém, 1. nedotahuje soubory do konce (95-97%), 2. nedaří se mi uložit nastavení pro další spuštění, vždy původní. V 1.64 fungovalo, knihovny jsem jako obvykle překopíroval, zkoušeno na Win7-32b i Win10-64b (stejné chování). Děkuji

**Comment by ibv** [comment]
Info o dokončeném stažení by mělo fungovat od verze 1.65, soubor je stažen celý,  pouze v seznamu stahování nedošlo k překreslení, když kliknete na jiný řádek v seznamu, tak se info o dokončeném stažení zobrazí?
Problém s uložením nastavení je zřejmě způsoben politikou UAC ve Winech, když ytd spustíte jako správce tak se nastavení uloží?
Na obr je ukázka funkčního stažení streamu

![ytd-5](https://user-images.githubusercontent.com/2648561/80457833-3ba00600-8930-11ea-8a7b-4287c5d43c59.png)
