### ISSUE TITLE
Download from YouTube creates 2 files

### ISSUE THREAD

**Issue by MyloshB** [ibv/YTD#38]
Dear IBV, 

could you, please, tell me, how to set creating only one output file (for example MP4) if www.youtube.com is used (for example https://www.youtube.com/watch?v=T3L3K4WC6Sw)?
Old versions created one output file (MP4), but the current version 1.65.20200514.0 creates the pair MPA and MPV.
And unfortunately I do not know, how to union this pair of files...

Thank you in advance, 
Mylosh B.

**Comment by ibv** [comment]
Hi,

YT now offers video as two separate streams, 
to merge into a single containers can be used ffmpeg:

**ffmpeg -i video.mpv -i audio.mpa -codec copy -shortest output.mp4**

Instructions for a similar situation are here (Czech only) [https://github.com/ibv/YTD/issues/14](https://github.com/ibv/YTD/issues/14)

Regards
IBV
