### ISSUE TITLE
Přidání http://videoarchiv.markiza.sk/

### ISSUE THREAD

**Issue by Jenikcz** [ibv/YTD#4]
Dobrý den,
šlo by přidat web http://videoarchiv.markiza.sk/, byl proveden redesign (ala Nova Plus) a již mají nový způsob vložených videí - segmentované ve formátu ts.
Děkuji
Jenikcz

**Comment by ibv** [comment]
Opraveno ve verzi 1.60

**Comment by ibv** [comment]
Další oprava ve skriptech 1.60.20180915.0
