### ISSUE TITLE
Novaplus

### ISSUE THREAD

**Issue by Dilinka16** [ibv/YTD#41]
Ahoj, pokud by to bylo možné, prosím o přidání možnosti nastavovat maximální rozlišení u novaplus.nova.cz jako to jde u České televize a Primy. Díky

**Comment by ibv** [comment]
Postup:
1. Klik na link (nova.cz) v YTD **prostředním** tlačítkem myši.
2. Zvolit max rozlišení.
3. Zadat číslo dle tabulky:
    Full HD (1920x1080) **5251072**
    HD (1280x720)  **3715072**    
    High (1024x576) **1667072**
    Med (640x360) **950272**
    Low (512x288) **540672**
4. Ukončit a znovu spustit YTD.
5. Začít stahovat.

Pokud se něco pokazí (stream se nestáhne), ukončit YTD, otevřít v editoru **ytd.xml** a umazat řádky v 
<Nova_cz>
**<max_video_width>**.....**</max_video_width>**
**<max_video_bitrate>**....**</max_video_bitrate>**
</Nova_cz>, 
uložit a pustit YTD.

**Comment by Jenikcz** [comment]
Dobrý den,
Zkoušel jsem popsaný postup ale něco asi dělám špatně. Bod 1 Klik na link (nova.cz) v YTD, když zadám odkaz s www adresou tak když kliknu levým tak nic a pravým otevře se mi menu různých možností nastavení. Prosím můžete blíže popsat jak na tento bod příp. i s obrázky ?
Děkuji

**Comment by ibv** [comment]
Menu pro rozlišení se vyvolá kliknutím **kolečkem** (**prostřední tl.**) na myšce.

![ytd-4](https://user-images.githubusercontent.com/2648561/87299522-787da100-c50c-11ea-9b06-b15a48c82daf.png)

**Comment by Dilinka16** [comment]
Výše popsaný způsob fungoval (v 1.65), ale větší část videí z Novy mi poté nejde přehrát (bez ohledu na to, jestli byla stažená s omezením nebo bez)

**Comment by ibv** [comment]
Nějaký konkrétní link na nefungující video?

**Comment by Dilinka16** [comment]
Např. https://novaplus.nova.cz/porad/dr-house/epizoda/29633-vii-10-dil-cukr-nebo-bic

**Comment by ibv** [comment]
Problem je DRM [https://cs.wikipedia.org/wiki/Digital_rights_management](https://cs.wikipedia.org/wiki/Digital_rights_management),

![n-1](https://user-images.githubusercontent.com/2648561/87776878-c524ed00-c828-11ea-8e1e-c4ea9a0d7848.png)
