### ISSUE TITLE
Rozhlas - změna lokace médii s odkazem prehravac.rozhlas.cz/audio/xxxxxxx

### ISSUE THREAD

**Issue by ladabohac** [ibv/YTD#42]
Odstavili server media.rozhlas.cz - např.: pro https://prehravac.rozhlas.cz/audio/2891066 je nyní URL média https://croaod.cz/download/c7d27b9a-9050-37a8-b760-39587a64bc86.mp3 . http://media.rozhlas.cz/_download/2891066 již nefunguje. Taky je v nejnovější verzi neaktivní ikona přispět na další rozvoj.

**Comment by ibv** [comment]
Opraveno v atualizaci skriptu 1.65.20200721.0,
aktualizovat podle navodu zde #5
