### ISSUE TITLE
videoarchiv.markiza.sk

### ISSUE THREAD

**Issue by Jenikcz** [ibv/YTD#43]
Nejdou stahovat videa z webu "videoarchiv.markiza.sk". Po vložení odkazu např. https://videoarchiv.markiza.sk/video/2-na-1/epizoda/28098-2-na-1-so-zuzanou-kubovcikovou-sebovou , hlásí "Chyba scriptu......".
Prosím, můžete se nato podívat ?
Děkuji.

**Comment by ibv** [comment]
Musíte chvilku vydržet, tak asi 14 dní nebudu schopen nic tvořit, pleskl jsem sebou na motorce a léčím se.

**Comment by ibv** [comment]
Opraveno v atualizaci skriptu 1.65.20201023.0,
aktualizovat podle navodu zde #5
