### ISSUE TITLE
YTD dnes nestáhlo irozhlas

### ISSUE THREAD

**Issue by vachuler** [ibv/YTD#45]
Dobrý den.
Dnes se mi nepodařilo stáhnout adresu: [https://vltava.rozhlas.cz/paolo-sorrentino-vsichni-maji-pravdu-mafie-drogy-a-neapol-v-premierove-cetbe-z-8350727](url)
děkuji Rob

**Comment by ibv** [comment]
Opraveno v atualizaci skriptu 1.65.20201126.0,
aktualizovat podle navodu zde #5

**Comment by vachuler** [comment]
Ahoj,
moc děkuju.
Robert

čt 26. 11. 2020 v 14:27 odesílatel ibv <notifications@github.com> napsal:

**Comment by vachuler** [comment]
Dobrý den.
Už zase Český rozhlas zkouší nějaké novinky.
Už delší dobu nešly stahovat soubory, které samy měly ikonku ke stažení
(takže to nevadilo), jindy se dala pro YTD přijatelná adresa najít v
možnostech ke sdílení.
Teď opět přicházejí s něčím novým.
https://dvojka.rozhlas.cz/zemrel-potomek-hrabeciho-rodu-zdenek-sternberg-o-svem-zivote-mluvil-s-noblesou-7484117
co nejde stáhnout.
Děkuji Robert Vachule


čt 26. 11. 2020 v 14:27 odesílatel ibv <notifications@github.com> napsal:

**Comment by ibv** [comment]
Opraveno v atualizaci skriptu 1.65.20210220.0,
aktualizovat podle navodu zde #5

**Comment by vachuler** [comment]
Dobrý den, nová verze mí zavála nadějí, ale bohužel marnou.
Budete mít prosím někdy čas se na to podívat?

https://vltava.rozhlas.cz/james-joyce-odysseus-velkolepa-parafraze-antickeho-mytu-v-romanu-irskeho-8669859#dil=
<https://vltava.rozhlas.cz/james-joyce-odysseus-velkolepa-parafraze-antickeho-mytu-v-romanu-irskeho-8669859#dil=3>

https://vltava.rozhlas.cz/dublinane-pusobive-a-ve-sve-dobe-kontroverzni-povidky-jamese-joyce-8669412#dil=5

https://vltava.rozhlas.cz/muj-zivot-s-hudbou-a-lidmi-kolem-ni-osudy-milose-stedrone-8666448#dil=5
Děkuji
Robert Vachule

**Comment by ibv** [comment]
Opraveno v aktualizaci skriptu 1.67.20220209.0,
aktualizovat podle navodu zde https://github.com/ibv/YTD/issues/5

**Comment by vachuler** [comment]
Dobrý den.
Strašně moc děkuji. Je to báječné (i když se to neumí vyrovnat s češtinou
:-). Ale radost by neměla být úplně zadarmo, tak i přesto je to skvělé.
(Kdybyste náhodou nevěděl o čem mluvím tak soubor Olga Tokarczuková - Svůj
vůz i pluh veď přes kosti mrtvých to stáhne jako:
1. d-u00edl Olga Tokarczukov-u00e1 Sv-u016fj v-u016fz i pluh ve-u010f
p-u0159es kosti mrtv-u00fdch.mp3
Ale zase to umí stahovat i dosud nepublikované soubory. No prostě paráda.
Robert Vachule

st 9. 2. 2022 v 15:40 odesílatel ibv ***@***.***> napsal:

**Comment by ibv** [comment]
Opraveno, stáhnout novou verzi [ytd-1.67-x32_64.7z](https://github.com/ibv/YTD/releases/download/v1.67/ytd-1.67-x32_64.7z) , rozbalit, vybrat správnou verzi ytd.exe (32/64) a ytd-defs.xml,
nebo spustit novou instalaci [ytd-1.67_x64.exe](https://github.com/ibv/YTD/releases/download/v1.67/ytd-1.67_x64.exe)

**Comment by vachuler** [comment]
Dobrý večer.
Krásný. Umí čésky, umí čésky. Nádhera moc děkuju.
A kouzelný je to, že to umí nejen před publikováním stáhnout audia, která
jsou tam k publikaci již připravena, ale i později stáhnout to Je nám líto,
ale k tomuto audiu již vypršela autorská práva.
k čemu jsou už smazány přístupové cesty, takže to nejde ani stočit přes
zvukovou kartu, ale oni zdá se tam ty soubory fyzicky nechávají.
Ještě jednou moc díky.
Robert Vachule

čt 10. 2. 2022 v 15:27 odesílatel ibv ***@***.***> napsal:
