### ISSUE TITLE
Problem with a TV station Ceska televize

### ISSUE THREAD

**Issue by hawkinsjim** [ibv/YTD#47]
Hello,
I wanted to download a video from ceskatelevize.cz and I wasn't succesful. URL is https://www.ceskatelevize.cz/ivysilani/13850114846-louskacek-vanocni-pribeh/
YTD writes: The download is prepareing or something similar (I have a Czech version. And nothing happens.
![image](https://user-images.githubusercontent.com/73299262/102909485-50aa4600-4479-11eb-8f38-0b918bbedd56.png)
Maybe they changed something. Please, could you look at it?
Regards
Jim

**Comment by hawkinsjim** [comment]
Hello.
I must apologize you. Today it works. It seems, that it was necessary to switch off the computer and to switch on. I downloaded it successfully.
Nice Christmas and a happy New Year.
Regards,
Jim

**Comment by ibv** [comment]
Hi Jim,
some streams are time-limited on CT,
BTW deleting/renaming the **locale** directory will change the YTD to default English version.

Nice Christmas and a happy New Year.
Regards,
Ivo
