### ISSUE TITLE
Problém s downloadem z české televize

### ISSUE THREAD

**Issue by MikiGrit** [ibv/YTD#48]
Mám problémy s tímto streamem: https://www.ceskatelevize.cz/porady/876764-jezis-nazaretsky/294381601260001/ (je k dispozici ještě 10 dní). Zdá se, že data se stáhnou všechna (soubor je zhruba velký jak bych očekával). Ale nejde přehrát, přehrávače mi vrací chybu. Díky.

**Comment by ibv** [comment]
V tomto případě se jedná o ochranu proti kopírování/šíření, DRM, 
některá videa si CT chrání, s tím se nedá nic dělat, leda by to někdo uměl rozkódovat ..
![ct-2](https://user-images.githubusercontent.com/2648561/103207817-934ba280-48ff-11eb-9fe7-fcb74ae94990.png)

**Comment by MikiGrit** [comment]
Aha, ok. Díky za info.
