### ISSUE TITLE
Stále nejde iPrima

### ISSUE THREAD

**Issue by Warpik74** [ibv/YTD#50]
Dobrý den,
Už asi týden mi nejde stahovat z iPrima, píše "Nepodařilo se najít stránku informací o mediu (EDownloadThreadError)". Odkaz přímo na stránku funguje, zobrazí se náhled k přehrání a jde přehrát. Zřejmě nějaká změna na stránkách, asi budu muset počkat na opravu, pokud to půjde. Děkuji

**Comment by ibv** [comment]
Zdravím,
nějaký konkrétní link?

**Comment by Warpik74** [comment]
Cokoliv z iPrima, kromě videopůjčovny a některých filmů. Třeba https://prima.iprima.cz/slunecna/biologicky-otec

**Comment by ibv** [comment]
Zkuste postup podle tohoto návodu [issues-24](https://github.com/ibv/YTD/issues/24)

**Comment by Warpik74** [comment]
Něco málo se nakonec podařilo, použít lze jen v nouzi, nehledě na složitost, zvlášť video a audio, není to klasický TS. Na "hromadné" stahování prostým zadáním nepoužitelné. Prosím co tam soudruzi zase zmrcasili, že to najednou nejde!
