### ISSUE TITLE
Nefunguje stahování z ivysílání

### ISSUE THREAD

**Issue by jkfhsdjkghsdjkghsdjkghsdjk** [ibv/YTD#53]
Dobrý den,mám problém se stahováním z české televize. Dnes jsem si chtěl stáhnout video z čt z videa se mi stáhlo 99% a zbytek se nestáhnul. Včera videa normálně stahovat šla ale dnes už nefungují, děje se to u záznamů z olympijských her. zkoušel jsem odinstalovat program a znovu zpátky nainstalovat ale ani tak to nejde.
Děkuji za vyřešení problému.

**Comment by ibv** [comment]
Můžete uvést nějaký odkaz na video?

**Comment by jkfhsdjkghsdjkghsdjkghsdjk** [comment]
https://www.ceskatelevize.cz/ivysilani/14023371863-xxxii-letni-olympijske-hry-tokio-2020/221471290102006-hodina-z-tokia
Dobrý den video se stáhne ale po spuštění ve VLC nejde obraz ani zvuk.
V pondělí ještě videa z olympiád fungovala ok ale od úterý už to nejde.

**Comment by ibv** [comment]
V tomto případě se jedná o ochranu proti kopírování/šíření, DRM, https://cs.wikipedia.org/wiki/Digital_rights_management,
některá videa si CT chrání, s tím se nedá nic dělat, leda by to někdo uměl rozkódovat ..

![o-20](https://user-images.githubusercontent.com/2648561/127456733-5be72a77-d5c8-48e8-989d-36a613792c33.png)

**Comment by jkfhsdjkghsdjkghsdjkghsdjk** [comment]
Děkuji vám za odpověď, tak to se nedá nic dělat. Já jsem s něčím takovým počítal že česká televize bude nějak blokovat olympijské hry. Proto mě překvapilo že do pondělí to šlo ale pak se na uložtu objevilo Slavnostní zahájení z pátka tak asi proto je zakódovala.
