### ISSUE TITLE
ČT nefunguje...

### ISSUE THREAD

**Issue by MyloshB** [ibv/YTD#54]
... asi je to dárek od škodičů z Dvořákovy bedny ke státnímu svátku.
Po zadání adresy zůstane YTD ve stavu "Připravuje se downlad".
Např. https://www.ceskatelevize.cz/ivysilani/12559285351-krajinou-domova-iii/219562260520008-stepi/

**Comment by jirkaza** [comment]
Děkuju mockrát i za všechny ostatní, zjistil jsem dnes stejný problém (překvapivě i se stejným souborem!) a popsaná úprava to řeší.

**Comment by bedazhavil** [comment]
Díky za opravu.

**Comment by MyloshB** [comment]
Mockrát děkuji Ivošovi za opravu!

**Comment by jirkaza** [comment]
Může někdo prosím vyzkoušet stažení hatetepees://wewewe.ceskatelevize.cz/porady/12648974609-uzasny-grand-canyon/21938256750/  ? **Odkaz je úmyslně nefunkční** (opravte si prosím první dva řetězce ručně), roboti bdí a tak je zbytečné je na to lákat...

Zkusil jsem to dvakrát, v obou případech se sice soubor stáhnul, ale nelze ho přehrát ani ve VLC, ani v jiných přehrávačích. Prostě je nějak porušený, oprava pomocí ffmpeg nepomáhá. Jiné odkazy ze stejného zdroje fungují normálně.

Díky.

**Comment by ibv** [comment]
Tady se jedná o ochranu DRM, viz [https://cs.wikipedia.org/wiki/Digital_rights_management](https://cs.wikipedia.org/wiki/Digital_rights_management)
![o-047](https://user-images.githubusercontent.com/2648561/139797457-5a06c285-1b46-4065-b94f-4496bf8606fa.png)

**Comment by LaSi-cz** [comment]
Připojuji se k ostatním, děkuji Vám za rychlé přizpůsobení programu nečekaným novým podmínkám.

**Comment by ibv** [comment]
No možná je radost předčasná, dle tohoto odkazu [https://www.lupa.cz/aktuality/ceska-televize-spusti-v-prosinci-novou-verzi-ivysilani/](https://www.lupa.cz/aktuality/ceska-televize-spusti-v-prosinci-novou-verzi-ivysilani/).
V diskuzi k tomu článku je i zmínka od xbmc-kodi-cz o možnosti přehrávat DRM obsah, nezkoušel jsem, ale kdyby měl někdo chuť, tak to může zkusit ... [https://github.com/xbmc-kodi-cz/plugin.video.ivysilani.cz/pull/2](https://github.com/xbmc-kodi-cz/plugin.video.ivysilani.cz/pull/2)

**Comment by LaSi-cz** [comment]
> No možná je radost předčasná, dle tohoto odkazu https://www.lupa.cz/aktuality/ceska-televize-spusti-v-prosinci-novou-verzi-ivysilani/. 

Tak na tento článek jsem narazila včera v noci, četla jsem jej (i komentáře) se stejnými pocity.  :(
Hledala jsem jiný zdroj informace, vč. webu CT, ale našla jsem jen tento starší článek:
[https://avmania.zive.cz/ceska-televize-letos-spusti-nove-ivysilani-nezustane-kamen-na-kameni](url)
... kde je popsáno 9 fází přechodu na nový systém, přičemž v době vzniku článku (02.2021) mělo proběhnout prvních 5 těchto fází.
Přiznám se, že obsah popisu fází je pro mne nesrozumitelný (text typu "mnoho slov o ničem"), takže nedokážu určit, která ta fáze se dotýká streamu.  :(

**Comment by LaSi-cz** [comment]
> V diskuzi k tomu článku je i zmínka od xbmc-kodi-cz o možnosti přehrávat DRM obsah, nezkoušel jsem, ale kdyby měl někdo chuť, tak to může zkusit ... [xbmc-kodi-cz/plugin.video.ivysilani.cz#2](https://github.com/xbmc-kodi-cz/plugin.video.ivysilani.cz/pull/2)

Jsem laik/samouk, obecně jsem pochopila, co je DRM-ochrana, ale netuším, zda-li je technicky nutné pro její vložení do videa soubor celý převádět/překlápět, což by byla časově dost náročná činnost, takže ty tisíce video-souborů v CT-archivu by nemohly být tímto opatřeny ze dne na den.
Přesto očekávám v brzké budoucnosti její rozšíření.  :(

**Comment by ibv** [comment]
V části releases je opravená verze v1.66 pro "novou" CT.
