### ISSUE TITLE
Nefunguje stahování z ČT od 6.12.2021

### ISSUE THREAD

**Issue by jkfhsdjkghsdjkghsdjkghsdjk** [ibv/YTD#55]
Od spuštění nového ivysílaní nelze nic stáhnout, zkopíruji odkaz a píše to že se připravuje download.
https://www.ceskatelevize.cz/porady/14587716865-svetovy-pohar-v-bobech-a-skeletonu-2021-22/221471291234260/
Děkuji za případné vyřešení problému.

**Comment by ibv** [comment]
Zatím prosím použijte postup popsaný zde https://github.com/ibv/YTD/issues/24,
funguje i na CT.

**Comment by ibv** [comment]
Zkušební beta verze 1.66 s opravou pro CT je ke stažení v části release
https://github.com/ibv/YTD/releases/download/v1.65/ytd-1.66-x64-beta.zip

**Comment by jkfhsdjkghsdjkghsdjkghsdjk** [comment]
Chtěl bych se zeptat jestli musím dělat novou instalaci když si stáhnu tuto novou verzi nebo lze jenom přepsat původní soubor? Já jsem jenom nahradil nový soubor za starý a stejně mi nejde stáhnout video z čt. 
Děkuji za odpověď.

**Comment by ibv** [comment]
Zkuste ještě nahradit soubor ytd-defs.xml ze zipu.
V release části je aktualizovaný zip soubor, přidal jsem tam i 64 bit dll knihovny pro případ, že někdo používal 32 bit verzi  a nemá potřebné knihovny pro regulární výrazy (pcre64.dll), 64 bit openssl knihovny  jsou v release také ke stažení.
Zkušební beta je 64 bit-ová.

**Comment by jkfhsdjkghsdjkghsdjkghsdjk** [comment]
Stahování z ČT funguje. Moc vám děkuji za pomoc.

**Comment by bedazhavil** [comment]
ČT jede. Díky.

**Comment by ibv** [comment]
Opraveno v dnešním vydaní v1.66, část releases.
