### ISSUE TITLE
Stažení z ČT se neukončí

### ISSUE THREAD

**Issue by clavvis** [ibv/YTD#56]
Dobrý den,

snažím se z ČT stáhnout poslední soutěžní večery StarDance. Stahování začne a pěkně běží, ale cca 8 MB před koncem se zastaví víc nic už neudělá ani po 10 min. čekání.

Teď už to zkouším jen na SD Kolem dokola, což je poměrně krátké. ale také se to před koncem zastaví.

https://www.ceskatelevize.cz/porady/12701251153-stardance-xi-kdyz-hvezdy-tanci/221544160470062/

Mám verzi 1.66 64 bit. Nejnovější verzi mi to ukazuje. Je stejná jako moje.

Nešlo by s tím něco udělat?

Předem děkuji.

**Comment by ibv** [comment]
Zkuste kliknout kliknout myškou na jiný řádek v okně pro stahování, měla by se zobrazit zpráva o konci stahování.
Uvedený odkaz o StarD používá DRM, [https://cs.wikipedia.org/wiki/Digital_rights_management ](https://cs.wikipedia.org/wiki/Digital_rights_management).

**Comment by clavvis** [comment]
Kliknutí na řádek s URL a pak na jiný řádek způsobí zobarzení zprávy o ukončení stahování.
Bohužel VLC stažený soubor vůbec nepřehraje a nedá žádné info. Zřejmě kvůli DRM.
A já bych si ten soubor přehrál rád, protože spouštění z iVysílání mne zdržuje.

**Comment by ibv** [comment]
K tématu DRM  na CT dopuručuji k prostudování diskuzi zde [https://forum.root.cz/index.php?topic=25636.0](https://forum.root.cz/index.php?topic=25636.0)
