### ISSUE TITLE
Verze 1.67 neaktualizuje konfig.soubor.

### ISSUE THREAD

**Issue by LaSi-cz** [ibv/YTD#57]
Dobrý den,
chtěla bych Vás informovat, že verze 1.67 (64bit) ze dne 05.02.2022: 
https://github.com/ibv/YTD/releases/download/v1.67/ytd-1.67-x32_64.7z
... mi neukládá seznam URL do konfiguračního souboru.
Podle všeho neukládá jakékoliv změny v nastavení, 
protože po zavření programu obsah a datum souboru YTD.xml zůstává stále stejný.

**Comment by ibv** [comment]
Na jaké verzi win (8,10,..)?  V jakém instalačním adresáři?
Novější verze windows už defaultně blokují zápisy do Program Files,...
Program YTD byl navržen v době, kdy tato omezení neplatila, zkusit pustit YTD odněkud mimo Program Files ..

**Comment by LaSi-cz** [comment]
Děkuji Vám za rychlou reakci.
-----
Edice: Windows 10 Home
Verze: 21H1
Build OS: 19043.1526
Výkon: Windows Feature Experience Pack 120.2212.4170.0
-----
Pro portable-verze programů vždy užívám svůj vlastní adresář mimo "ProgramFiles", 
takže poslední verze YTD je v "C:\Portable-S\YTD_1.67_(64b)\"
a předposlední veze je v "C:\Portable-S\YTD_1.66_(64b)\".
Adresář s novou verzí vždy vytvářím z kopie předeslé verze, do něhož pak nakopíruji(přepis) všechny soubory nové verze.
-----

**Comment by ibv** [comment]
Teď nevím, jestli se problém podařilo vyřešit, nebo je to stále nedořešeno?
Při testování aplikace se mi údaje do ytd.xml zapisují.

**Comment by LaSi-cz** [comment]
Čekala jsem na Vaši odpověď typu rady, kde-co-jak ještě zkontrolovat, prověřit.
Protože atributy všech dotčených adresářů a souborů nebyly nastaveny na "ReadOnly" nebo "System".
Neviděla jsem tedy žádnou další možnost, jak coby prostý uživatel chování programu "YTD" ovlivnit.
Nyní jsem tedy zkusila YTD přesunout do jiného nově založeného adresáře a vskutku zápis do YTD.xml začal fungovat !! 
(Nechápu, v ČEM mohla být příčina!?)
Takže problém vyřešen.
