### ISSUE TITLE
Ceska televize serial stahuje porad jeden dil

### ISSUE THREAD

**Issue by cerdacz** [ibv/YTD#59]
https://www.ceskatelevize.cz/porady/13247865949-napeceno/
resp.
https://www.ceskatelevize.cz/porady/13247865949-napeceno/219265080040001/
byt na webu se prehraje korektni dil, pres YTD se stahuje uplne posledni dil - francouzske tousty :)

Zkouseno s v 1.66 a 1.67 na win7.

**Comment by IntEA31** [comment]
Ahoj. ČT upravila interface playlist rozhraní, bude potřeba úprava YTD v CT downloaderu - metoda AfterPrepareFromPage():

```
if not GetPlaylistInfo(Http, Referer {Page}, PlaylistType, PlaylistID) then  // playlistID = numeric ID of movie, playlistType unused
    SetLastErrorMsg(ERR_FAILED_TO_LOCATE_MEDIA_INFO_PAGE)

else if not DownloadPage(Http,
                           'https://www.ceskatelevize.cz/ivysilani/ajax/get-client-playlist/',
                           {$IFDEF UNICODE} AnsiString {$ENDIF} (
                           'playlist[0][type]=episode&playlist[0][id]='+PlaylistID+'&playlist[0][startTime]=0'+                        
                           '&requestSource=iVysilani&type=dash&canPlayDRM=false&requestUrl=/ivysilani/embed/iFramePlayer.php'),
                           HTTP_FORM_URLENCODING_UTF8,
                           ['x-addr: 127.0.0.1', 'X-Requested-With: XMLHttpRequest'],
                           PlaylistUrlPage,
                           peUtf8
                          )
```
a metoda GetPlayListInfo() nehledá playlist ID ve stažené stránce, ale z URL adresy média ve tvaru např. https://www.ceskatelevize.cz/porady/10818759487-chuggington-vesele-vlacky/221384609200026/ pomocí regexu 
`  REGEXP_PLAYLIST_INFO = '\s*/(?P<ID>\d+)?/?$';`

navíc pro přímé spouštění ČT downloaderu upraven URL match regex na 
`  URLREGEXP_ID =        REGEXP_COMMON_URL_PREFIX + '(?:ceskatelevize|ct24)\.cz/(porady|ivysilani)/.+';`

Rychlý fix "works for me" z aktuálních zdrojů, třeba se bude hodit autorovi k zakomponování do nové verze. Testováno jenom s TS streamem, MPEG DASH nepoužívám. Omlouvám se za absenci patche, třeba příště ;-)

**Comment by ibv** [comment]
Díky za pomoc, mám opraveno v src, v "**historicky**" krátké době bude publikována nová verze 1.68

**Comment by ibv** [comment]
Opraveno v dnešním vydání verze 1.68, odkaz zde https://github.com/ibv/YTD/releases/tag/v1.68
