### ISSUE TITLE
Videoarchív Markiza.sk (Televízne noviny)

### ISSUE THREAD

**Issue by kubalav** [ibv/YTD#6]
Sťahovanie z markiza.sk funguje, ale konkrétne TN nie.
Testovacia URL:
[http://videoarchiv.markiza.sk/video/televizne-noviny/epizoda/14446-televizne-noviny](url)

**Comment by ibv** [comment]
Stream TN nyní dávají jako jednotlivé epizody (samostatné streamy), mám problém spíše designový, dát výsledek jako jednotlivé soubory nebo to slepit do jednoho souboru?

**Comment by kubalav** [comment]
Myslím si, že dať to do jedného súboru je rozumnejšie (aspoň pre mňa). Na druhú stranu, ak to bude rozkúskované, tak spojiť to už nie je problém. Ale je potrebné to brať pre všetkých, takže asi tie jednotlivé súbory ako to bývalo kedysi v YTD.

**Comment by ibv** [comment]
Opraveno ve skriptech 1.60.20181114.0, 
aktualizovat skripty v dialogu About (poslední ikona v řadě), potom kliknout na číslo 1.60.20181114.0,
vystoupit a nastoupit do programu YTD a mělo by to jít.

**Comment by kubalav** [comment]
Ďakujem, funguje.
