### ISSUE TITLE
iVysilani - detektivky

### ISSUE THREAD

**Issue by cerdacz** [ibv/YTD#63]
Nektere detektivky ted nove padaji do varovani o veku, napr. 
https://www.ceskatelevize.cz/porady/10354229723-pripady-1-oddeleni/213512120200006/ 
ci 
https://www.ceskatelevize.cz/porady/10571003683-vrazdy-v-kruhu/21351212031/

**Comment by ibv** [comment]
Mám opraveno v testovací verzi, ale nestíhám vydat další opravenou verzi.

**Comment by cerdacz** [comment]
Parada diky.

Slo by prosim cely zde publikovany kod spojit od Lazarus projektu ?
Pokousel jsem se o to, ale na ciste instalaci mi to hazelo spoustu chyb (at uz s konverzi stareho Delphi projektu nebo bez).

**Comment by ibv** [comment]
Ano, mělo by to fungovat i na win verzi, názvy souborů se mi tam mixují z linuxu. Linux obecně rozlišuje malá velká písmena v názvech souborů. Opravím v další verzi, zatím nemám hotové opravy pro Prima-Zoom.

**Comment by ibv** [comment]
Opraveno v dnešním vydání verze 1.69, odkaz zde https://github.com/ibv/YTD/releases/tag/v1.69
