### ISSUE TITLE
Změna domény novaplus.cz

### ISSUE THREAD

**Issue by Jenikcz** [ibv/YTD#64]
Dobrý den,

Mohu požádat o úpravu, webmaster změnil www doménu z novaplus.cz na tv.nova.cz, kde je archiv videí Nova TV.

Děkuji.

S pozdravem,

Jenikcz

**Comment by ibv** [comment]
Opraveno ve skriptech verze 1.69.20220803.0,
aktualizovat obvyklým způsobem.
