### ISSUE TITLE
Pricina padani YTD je asi vyresena a zvuky se neprehravaji i mimo okno programu

### ISSUE THREAD

**Issue by MichalSuchy** [ibv/YTD#65]
Dobrý den. Tak jsem zřejmě objevil příčinu padání YTD. Když nezaškrtnu, aby po stažení mazal dokončená stahování ze seznamu stahování, tak nespadne. A ještě jsem zjistil, že když nejsem v okně YTD a dokončí se stahování nebo dojde k chybě, tak se zvuky přehrají až po vstupu do okna s programem a ne i mimo něj.

**Comment by ibv** [comment]
Zdravím, potvrzuji uvedené chování u zvukových znamení, pokud není fokus na YTD, tak zvuk nepřehrává, zkusím zapátrat po příčině.
Druhý problém s chybou stahování se mi nepodařilo nasimulovat, pokud se jedná o volbu v konfiguraci "Automaticky mazat dokončené downloady".
![o-008](https://user-images.githubusercontent.com/2648561/185070329-51c4d952-2072-43fc-a4ea-12eee174c42f.png)
