### ISSUE TITLE
Změna na webu tv.nova.cz

### ISSUE THREAD

**Issue by Jenikcz** [ibv/YTD#66]
Dobrý den,

Mohu požádat o úpravu, webmaster asi změnil programování videí v archivu, po zadání videa do programu vyskočí hláška v části Průběh stahování "Chyba skriptu: Žádná podmínka nebyla splněná. <if><condition type="regexp" ..........

Děkuji.

S pozdravem,

Jenikcz

**Comment by ibv** [comment]
Opraveno ve skriptech verze 1.69.20220825.0,
aktualizovat obvyklým způsobem.
