### ISSUE TITLE
Rozlišení videa

### ISSUE THREAD

**Issue by Jenikcz** [ibv/YTD#67]
Dobrý den,

Chci se Vás zeptat k rozlišení stahovaného videa, u následujících dvou příkladů se mi u jednoho nestáhne vysoké rozlišení (i když je v manifestu uvedené) :

- stáhne se vysoké rozlišení
https://tv.nova.cz/porad/ordinace-v-ruzove-zahrade-2/epizoda/33434-735-dil-uz-te-nemiluju

část z manifestu
Representation id="p0va0br1193349" codecs="avc1.4d401f" width="1024" height="576" sar="1:1" bandwidth="1193349"
Representation id="p0va0br597524" codecs="avc1.4d401e" width="640" height="360" sar="1:1" bandwidth="597524"
Representation id="p0va0br994851" codecs="avc1.4d401e" width="768" height="432" sar="1:1" bandwidth="994851"
Representation id="p0va0br2489452" codecs="avc1.4d401f" width="1280" height="720" sar="1:1" bandwidth="2489452"

- nestáhne se vysoké rozlišení
https://tv.nova.cz/porad/ordinace-v-ruzove-zahrade-2/epizoda/33444-736-dil-zakazane-ovoce

část z manifestu
Representation id="p0va0br971816" codecs="avc1.4d001f" width="768" height="432" sar="1:1" bandwidth="971816"
Representation id="p0va0br402899" codecs="avc1.4d001f" width="512" height="288" sar="1:1" bandwidth="402899"
Representation id="p0va0br683722" codecs="avc1.4d001f" width="640" height="360" sar="1:1" bandwidth="683722"
Representation id="p0va0br1464369" codecs="avc1.4d001f" width="1024" height="576" sar="1:1" bandwidth="1464369"

V programu mám nastavené od instalace rozlišení AUTO

Prosím, je možné se na tuto anomálii podívat ?

Děkuji.

S pozdravem,

Jenikcz

**Comment by ibv** [comment]
Zdravím,  tady se domnívám, že závada není na "vašem přijímači", ale že je něco špatně přímo na stránkách Novy, 
posílají špatná data. YTD stahuje HLS stream, ne MPEG-DASH.
