### ISSUE TITLE
CT stale o krok pred YTD

### ISSUE THREAD

**Issue by MyloshB** [ibv/YTD#70]
Mily pane Ivosi, chtel bych Vas poprosit o vylepseni YTD stran CT, kde nefunguje stahovani z "playeru", viz tyto 2 ukazky:

https://art.ceskatelevize.cz/inside/tvare-folku-jaroslav-hutka-GnHM3
https://www.ceskatelevize.cz/porady/14639544415-slysim-poprvy/bonus/42515

Dekuji Vam jiz predem za laskavost, drzim palce a zdravim, Mylosh B.

**Comment by ibv** [comment]
Zdravím,
opraveno v dnešní (28.3.2023) verzi [YTD v1.70](https://github.com/ibv/YTD/releases/tag/v1.70).
Pro spávnou funkci se musí povolit MPEG-DASH stream v nastavení stahovačů (CT)  .
Po stažení je třeba spojit video a audio do kontejneru dle návodu  [zde:](14)

**Comment by cerdacz** [comment]
Bohuzel nefunguje, exe ma datum 28.3.2023, ale v About je verze 230317, stejne tak je tam 230317 vedena jako posledni.

**Comment by ibv** [comment]
To je divné, verze **1.70.0.2** funguje dle požadavků.
Můžete ověřit, zda používate tuto verzi (1.70.0.2) ?
![o-012](https://user-images.githubusercontent.com/2648561/228434707-013f1ff6-4f57-4d92-97f4-2ff812ce092a.png)
![o-013](https://user-images.githubusercontent.com/2648561/228434738-553f81c5-b765-465a-a5eb-40259eb4484b.png)

**Comment by cerdacz** [comment]
Mam stejnou verzi, nainstaloval jsem i do noveho adresare a mezi testy smazal config a pak jen zaskrtnul mpeg u ct.

![image](https://user-images.githubusercontent.com/61126731/228442181-01c6ce55-53aa-4229-b4ea-2998d015e15f.png)

**Comment by ibv** [comment]
Hmm, to jsem z toho jelen Větrník, vůbec netuším kde může být problém.
Můžet zkusit, jestli se začne korektně stahovat tento odkaz, případně nějaký jiný z CT?
[https://www.ceskatelevize.cz/porady/10179604652-krasy-evropskeho-pobrezi/210382545670013/](https://www.ceskatelevize.cz/porady/10179604652-krasy-evropskeho-pobrezi/210382545670013/)

**Comment by cerdacz** [comment]
Kdyz jsem tam dal jen odkaz vyse tak jsem skoncil na "Ceka se"

**Comment by ibv** [comment]
Nemáte v programu YTD zapnutou http(s) proxy?
![o-012](https://user-images.githubusercontent.com/2648561/228757433-d69f587a-7e73-4f7e-9348-e6fb33d08413.png)

**Comment by cerdacz** [comment]
Nemam, zkousel jsem i zapnout a pak vypnout, se stejnym vysledkem.

**Comment by ladis2000** [comment]
Mám úplně stejný problém. Video z České televize nejde stáhnout.

**Comment by ibv** [comment]
Zdravím, nějaký konkrétní link?
Cvičně jsem zkusil tento odkaz [https://www.ceskatelevize.cz/porady/21947-tri-veterani/](https://www.ceskatelevize.cz/porady/21947-tri-veterani/) a funguje **HLS** i **MPEG-DASH** stahování.
![o-55](https://user-images.githubusercontent.com/2648561/230878138-1ee9c0ba-0b54-48e7-83c3-30566dd719d4.png)
Zkuste vypnout podporu MPEG-DASH u CT a stahovat pomocí HLS (defaultní volba u CT).

**Comment by cerdacz** [comment]
![image](https://user-images.githubusercontent.com/61126731/230927030-9388100c-fe37-4372-87ca-588f93aff4a5.png)
bez DASH

**Comment by cerdacz** [comment]
![image](https://user-images.githubusercontent.com/61126731/230927549-870cf8db-525d-4389-86b2-f66e5f7a89cc.png)
MPEG Dash

**Comment by cerdacz** [comment]
sys info: Win7 x64, eset, k-lite codec pack (popr. se ptej, co dalsiho by mohlo mit vliv)

**Comment by ibv** [comment]
Tak pokud je nasazen Eset, zaměřil bych pátrání tímto směrem. Zkusit poštelovat chování Esetu pro **SSL/TLS a web** nebo ho na chvilku vypnout a zkusit stahování.
V práci jsme několikrát řešili podivné chování https komunikace a většinou byl problém v Esetu.

![o-012](https://user-images.githubusercontent.com/2648561/231079120-b127b74b-e666-4e4d-ab15-a285a921a672.png)

![o-013](https://user-images.githubusercontent.com/2648561/231079199-7c996a91-d321-417d-a2b8-9607c22a9df1.png)

**Comment by cerdacz** [comment]
Dekuji za napad, ale jak pri vypnuti ochrany na 10 minut, tak jen pri vypnuti SSL / TLS a scanneru se stahovani chova porad stejne :(.

**Comment by ibv** [comment]
Tak ještě zkusit pár kroků.
1. V prohlížeči přehrání videa z ČT normálně funguje?
2. Ověřit v YTD, že funguje SSL. Jednoduchý test pro ověření fungování SSL je kliknout na ikonu About.
   Pokud se objeví text nenalezeno, viz obr.,tak jsou SSL knihovny nekompatibilní.
![1](https://user-images.githubusercontent.com/2648561/231430804-20e6a392-efcf-40ad-ae66-fba08fc41608.png)
3. Prozkoumat možnosti nastavení Win7 firewallu, např. [zde](https://blink.ucsd.edu/technology/security/user-guides/firewall/windows7-a.html#2.-Manually-allow-programs-thro) pro YTD.exe, případně FW vypnout a zkusit stahovat pomocí YTD

**Comment by ibv** [comment]
Zkuste předchozí verzi YTD 1.69, rozbalit [YTD 1.69](https://github.com/ibv/YTD/releases/download/v1.69/ytd-1.69-x32_64.7z) a použít ytd-64.exe.
Pokud stažení  z CT proběhne ok, bude problém v nové verzi 1.70, jenom netuším jaký, protože u mě na Win10 verze 1.70
funguje korektně.

**Comment by cerdacz** [comment]
Chova se to stejne s 1.68, 1.69 i 1.70 :(.

**Comment by ibv** [comment]
V části release je cmd verze YTD-64, odkaz [zde](https://github.com/ibv/YTD/releases/download/v1.70/ytd-x64-cli.zip).
Zkusit pustit s parametrem: **ytd-x64.exe -nd https://www.ceskatelevize.cz/porady/1050351371-utek-do-bezpeci/** 
v ytd.xml by mělo být toto:

![o-015](https://user-images.githubusercontent.com/2648561/232469699-c3a9b825-f7c5-440a-a6c3-44f5e506563a.png)

Výsledek by měl být podobný jako na obr. 

![o-014](https://user-images.githubusercontent.com/2648561/232469782-b5497bc9-a42b-4dbf-ac73-2ed5ff681279.png)

**Comment by Toxman3** [comment]
Ahoj,
mám (cca poslední 1-2 týdny) stejné popisované problémy tak, jestli můžu, upřesním:
V XML u max_video_width jsem měl 0, změnil jsem na 1920, ale v obou konfiguracích CLI verze skončila vypsáním modrého řádku s linkem ...1050351371-utek-do-bezpeci/ (testovány i jiné odkazy) a čeká a čeká, dokud to nebrejknu. K vypsání Media title, File name a Content URL se nedostane ani za 15 min...

Pro upřesnění... klasickou okenní verzi jsem zkoušel na dvou různých W 10 (jedny starší, jedny aktuální) na dvou rozdílných sítích (jedna mikrovlná/bezdrátová, jedno mobilní připojení), ale obě od O2. Firewall pouze Windowsácký (a i ten jsem zkušebně vypnul - bez výsledku).

Je ale třeba dodat, že občas, výjimečně (když jsem měl ve frontě více stahování z ČT) a frontu jsem různě pausoval, odpausovával, stopnul/refreshnul, přidával a odebíral odkazy a YTD ukončoval a spouštěl, náhodně se některý z odkazů uprostřed chytil (někdy i 3 zároveň), když se stahování těch živých odkazů dokončilo, zase nic - fronta tuhá a lavírování může začít nanovo.

Odhaduji že na 1 stažený odkaz je tak 50 (ale spíš mnohem více) těch, které hlásí jen "Připravuje se download". Do toho (zvlášť po prvním smazání odkazu), pro YTD typický Acces Violation (ale takové prkotiny teď neřeším ;)

Na verzi 1.70 jsem přecházel hlavně proto, že jsem myslel, že tyhle podivnosti řeší... :)

**Comment by cerdacz** [comment]
![image](https://user-images.githubusercontent.com/61126731/232598318-7267e10e-bb8d-4caa-b158-9705b8ffd7d5.png)

**Comment by Toxman3** [comment]
Osobně to vidím na nějaký problém v parseru (nebo jak nazvat ten "dolovač" odkazů...), který se většinou nechytá (na něčem se zasekne a stojí), protože když se to náhodou rozjede, tak to jede až do konce jako po másle.

**Comment by ibv** [comment]
To je zajímavá myšlenka s tím parsováním, v podstatě jde o regulární výrazy a vyzobávání z html.
Bohužel se mi stále nedaří nasimulovat zmiňovaný problém.
Pause/start může v některých případech zlobit, je tam rozjeto více vláken a při některých pokusech dojde k hlášce access  violation.

**Comment by ibv** [comment]
Jj, zkusím něco takového vypotit.

**Comment by Toxman3** [comment]
Ono s tím HTMLkem to může být dost ošemetné. Když jde o statický zdroj, tak to je pro parsování půl bídy, ale v dnešní době, kdy do toho kódu může dynamicky (za běhu) vrtat kdejaký JavaScript (a to za jistých podmínek i z jiných zdrojů - teoreticky i přímo od O2) se v podstatě asi nějak "musí" emulovat chování prohlížeče (běh toho skriptu).

Bez těch "vrtacích" scriptů takové weby nemusí vůbec fungovat (nebo za jistých okolností nemusí fungovat korektně). Ty skripty mohou ověřovat kde co (od OS a jeho verze až po prohlížeč a spoustu dalších "důležitých prkotin").

Osobně se mi vždycky líbilo, jak umí YTD většinou chytře přeskakovat předřazené "reklamy". Při parsování stránek jsem se ale dostal nejdál asi k nějakému neproniknutelnému blobu, takže mnohem rychlejší bylo sledovat stránkou skutečně načítané soubory a jejich URL, protože tu práci odtemňování jejich záměrně zatemněných odkazů už odedřely skripty. :)

**Comment by alum300** [comment]
Pane ibv, dovolte mi dotaz: Používáte k testování YTD internetové připojení od O2, nebo k tomu máte jiného poskytovatele? Mám totiž dojem, že příčinou výše popisovaných problémů není tentokrát ČT, nýbrž O2. Já mám připojení od O2 s tarifem „Bronze“ (bez O2 TV), a s únorovou fakturou jsem obdržel dodatek, z něhož cituji:

„Oznámení o změně smluvních podmínek: (...) u služby Internet v pevném místě rušíme tarif Internet HD Bronzový (...) a nahradíme ho dne 1.5.2023 tarifem Internet HD Bronzový s O2 TV (...) a vy tak budete moci sledovat současně na jednom zařízení nejméně 30 televizních programů, z toho kromě volně šířených (...) i minimálně jeden dětský, jeden filmový a jeden dokumentární. (...) V případě, že se změnou nesouhlasíte, můžete službu Internet v pevném místě (...) do data 30.4.2023 bez sankce zrušit.“

Za několik dní po doručení tohoto oznámení, přesně ode dne 15.3.2023, mi přestal fungovat program YTD v1.69 x64 (fpc). Nic nepomohl ani přechod k nové verzi 1.70 (28.3.2023). YTD se v mém případě nyní chová podobně, jak to zde přede mnou popsali ostatní uživatelé. O2 tedy zřejmě nasadil nový software již v průběhu března, i když v mém případě prozatím neuvolňuje nabídku vybraného filmu ani vybraného dokumentu a vyčkává s tím asi do 1. května. Přehrávání běžného iVysílání mi v Opeře funguje.

Pokud jde o postup, který vysvětluje v komentáři cerdacz (Apr 13, 2023), použitím tak získaného odkazu lze dostat soubor „*-pc.mpd“, který obsahuje parametry pro přehrávání. Nebylo by možné naučit program YTD, aby ho dovedl přečíst a použít? 

Příklad („https://www.ceskatelevize.cz/porady/10122427178-udalosti-v-regionech-brno/323281381990414/“):

![image](https://user-images.githubusercontent.com/131173258/232815547-e768f02a-7af8-49ad-b289-e6c69f256a57.png)



`

**Comment by ibv** [comment]
Zpracování manifest DASH souboru (.mpd) YTD umí, více je popsáno [zde](24).
Připojení na net máme v práci přes O2, doma mám T-Mobile LTE, na obou spojeních stahování funguje.
YTD vystupuje vůči stream serveru jako obyčejný http(s) klient, používá funkce GET, POST z http(s). 
Takový větší rozdíl oproti prohlížeči je fitrace (vynechání) javascriptů a jiný User Agent string, jinak se v komunikaci tváří jako webový klient.

**Comment by Toxman3** [comment]
@ibv je pravděpodobné, že cokoliv z uvedeného, tedy jiný User Agent, než mají běžné podporované prohlížeče, tak chybějící JavaScript, může mít vliv na funkčnost (a evidentně závisí i na poskytovateli/místě/způsobu... připojení). Mám pocit, že O2 (ale i ostatní poskytovatelé) občas leccos (někdy a někde) filtrují.

S tím .MPD mě napadá... Pokud by jej YTD uměl dostat ze zdroje, tedy počítám z čistého HTML, mohl by jej získávat na samotném začátku stahování (a případně obnovit při /delším/ přerušení), jen mám obavu že získat .MPD bez JS nepůjde. Pokud se mýlím, ?možná? by to přece jen byla cesta (před stahováním, příp. v průběhu, by se musela vytvořit nová sešna).

Během stahování a při vygenerování nového .MPD se myslím jednotlivé dílky "skládačky" ani jejich čísla nemění, mění se jen odkaz a nějaké ID (DNA nebo jak to nazývají), takže ani přegenerování .MPD by možná nemuselo správné navázání dat zhatit.

**Comment by cerdacz** [comment]
mpd reseni tez nefunguje :(
![image](https://user-images.githubusercontent.com/61126731/233071467-d4b2514a-8bbb-4c9d-9ddc-3440a112203f.png)

**Comment by Toxman3** [comment]
@cerdacz  Ten požadavek GET ale vypadá trochu jinak:
https://ivys-vst16-5.o2tv.cz/atip/c50d725a1e3fd147cbfebb14bc28e63f/1681909985347/61924494878125885-pc.mpd

Připomíná "skutečný" soubor, to co uvádíte je spíše Location z toho .MPD
Pokud zadám do YTD přímo odkazovaný soubor, je výsledek:
![YTD003](https://user-images.githubusercontent.com/131013927/233087696-30eb7983-d033-435a-b5a3-c49fde34e181.png)

Ale stejně to hned skončí a nic se nestáhne. Dají se nějak vypsat správné parametry pro CLI verzi?

**Comment by Toxman3** [comment]
Ještě doplním, že včera mi šlo jisté .MPD stáhnout snad i po několika hodinách, to výše vypršelo za pár minut (takže už nefunguje).
Možná to má souvislost s kódováním některých pořadů ČT (zahraničních zvlášť).

**Comment by cerdacz** [comment]
@Toxman3 parametry se daji vypsat -?, ale moc jich neni ;)

**Comment by Toxman3** [comment]
@cerdacz Jéé díky - to mě nenapadlo... A já furt /? /h /help ;)

**Comment by Toxman3** [comment]
Ftom případě to ta CLI verze z .MDP (něco) skutečně stahuje...

**Comment by Toxman3** [comment]
Bez zbytečných dalších parametrů - rovnou předávám to .MPD

![YTD004](https://user-images.githubusercontent.com/131013927/233095595-feb87c5d-8383-434a-be20-26ca6ec1ee95.png)

**Comment by ibv** [comment]
V release části je ke stažení dev verze pro ČT, stahujte [zde](https://github.com/ibv/YTD/releases/download/v1.70/ytd-1.70-dev_x64.zip).
**UPOZORNĚNÍ:  Nepoužívat pro běžné stahování, určeno pouze k otestování funkčnosti komunikace z ČT !**
Celý obsah zip souboru nakopírovat např. do C:\YTD, obsahuje knihovny OpenSSL 3.1.
Spustit stahování z CT a za chvíli ho zase stopnout, aby log soubor **ytd.log**, ve kterém je zachycena komunikace se serverem CT, moc nenarostl.
CLI verzi už nepoužívejte, moc informací nenabízí.

**Comment by cerdacz** [comment]
@Toxman3 kodovani bylo zminovano jiz nekolikrat a je to zpusob DRM a zatim prekonatelny jednoduse neni (otazkou je, jestli pripadne prolomeni by neprineslo vic problemu nez uzitku ... zmeny na strane CT, popr neprijemnosti pro vyvojare).

**Comment by Toxman3** [comment]
@cerdacz Díky Vám za info. :) Vcelku mi je jasné, že je to DRM, a že je to ze strany ČT zcela záměrný naschvál. Není mi ale jasné proč ČT (mimochodem placená z našich daní) takovéto skvělé kousky předvádí čím dál častěji a to i u docela starých českých/československých pořadů. Copak tenkrát z našich daní placená nebyla? Kdyby podobné vylomeniny (a časové omezení sledovatelnosti) pořád nevymýšleli, ani by moc nebylo potřeba stahovačů (snad jen pro off-line sledování). Těch hnusných DRM totiž, zdá se, přibývá jako hub po dešti a kdo ví, zda za chvíli nebude takto zmršeno všecko...

V sektoru distribuce software, zvláště her, jsou společnosti, které si (především) na DRM postavily svůj business (jmenujme např. Steam, Epic, EA...). Ale kupodivu se prosadila i polská společnost GOG, která naopak distribuuje placené, a to dokonce i nové hry zcela bez DRM (občas s výjimkou síťových služeb, kde to technicky nemusí být jednoduše možné). A ono to funguje - a nekrachují. Ostatní SW společnosti včetně Microsoft, Adobe, Maxon... jsou typičtí tvrdí prosazovači DRM, ale přitom mnoho jejich softwaru (ne-li většina či všechen) by vůbec, nebo téměř vůbec, nefungovala, kdyby sami nepoužívali různé open-source knihovny pro kde co, které mohli použít -světě div se- jen proto, že je jejich autoři zveřejnili bez DRM a to dokonce v otevřeném kódu pro všechny bez (větších) omezení.

Ale to jsem odbočil - zpět k ČT. U typu DRM, který používají v ČT na své pořady se nemůže jednat o prolomení (v pravém slova smyslu). O prolomení by šlo, nebyly-li by k dispozici klíče (např. placené pořady u neplatícího uživatele). Zde je však DRM použito pro všechny uživatele, tudíž všichni uživatelé musí nutně mít v prohlížeči při přehrávání přítomen dekódovací klíč.

Vím, že to vůbec není jednoduchá záležitost protože, jak jsem se už zmínil, všechno končí u nějakého neproniknutelného blobu v paměti prohlížeče a u kódu, do kterého vrtá možná desítky skriptů. Bylo by nutné (ve velké míře) při stahování, a patrně i při přehrávání, emulovat prohlížeč. Při emulaci by se ale musely přesměrovat zdroje na lokální a případně i vracet nějaká stará odchycená časová razítka atp.

Je mi jasné, že pokud to bude aktivně dynamicky zašifrované "střípek po střípku", bude to nejspíš mnohem větší problém. Nemám to ověřené a možná se mýlim, ale řekl bych, že na takové šifrování nemá ČT ani zdaleka výpočetní kapacity, a že jen vrací předem staticky zakódovaný nasekaný "stream" (s jedním nebo nemnoha neměnnými klíči). Pak by každý jeden, kdekoliv stažený pořad, mělo být možné rozkódovat stejným (v určitou dobu v podstatě veřejně dostupným) dekódovacím klíčem (pro ten konkrétní pořad nebo nějaký balík pořadů).

Pokud však kódují každou instanci prohlížeče za běhu (a nepodaří se tyto klíče odchytit právě v okamžiku přehrávání), stažený soubor je jen bezcenná hromada zašifrovaných dat s dávno ztracenými klíči.

Tím jsem se spíše chtěl informovat, zda-li v dané oblasti nedošlo k nějakému novému posunu... Proti těžkým kalibrům (DRM) bude ale patrně nutné časem nasadit jiné těžké kalibry. Tím nemyslím jich skutečné "prolomení", které je mimo dnešní technické možnosti - pokud, pane cerdacz, nemáte doma pod stolem nějaký, právě nevyužitý kvantový počítač. Já jsem se pod svůj stůl díval a nemám ho tam, asi jsem ho někomu půjčil... ;)

Napadá mě, že zrovna na takové netriviální účely by možná mohla časem posloužit umělá ta... AI jaj AI - ta moje hlava - no jak se tomu jenom říká... hloupá umělá inteligence, která by ten balast regulérních dekódovacích skriptů zvládla (tedy ne ve smyslu regulárních výrazů ;).

Dá se teda dopředu nějak jednoduše zjistit, co je kódováno (a ušetřit si případné stahování)?

Omlouvám se za trochu delší a trochu off-topic.

**Comment by ibv** [comment]
Hodil jsem do release části opravenou verzi YTD 1.7.0.3, ke stažení [zde](https://github.com/ibv/YTD/releases/download/v1.70/ytd-1.70-x32_64.7z).
Používá knihovny OpenSSL 1.1, pro eliminaci vlivu knihoven OpenSSL 3+.
Při laborování s logováním jsem našel chybku ve zpracování stahování z CT, v GET funkci . 
Po potvrzení funkčnosti nahrám na github verzi už s knihovnami OpenSSL 3+.
Je ale divné, že u mě stahování procházelo, bylo by možné v této souvislosti zjistit výrobce a model síťové karty?
V linuxu mám Realtek RTL8111/8168/8411 PCI Express, na Winech používám VirtualBox, kde je nastavena karta 
Intel PRO/1000 82540EM.

K tématu DRM na CT doporučuji k prostudování [zde](https://forum.root.cz/index.php?topic=25636.0) a [zde](https://github.com/xbmc-kodi-cz/plugin.video.ivysilani.cz/pull/2)

**Comment by cerdacz** [comment]
Ja mam v pc starou USB kartu - Realtek RTL8188SU Wireless LAN 802.11n USB 2.0 Network Adapter.

**Comment by Toxman3** [comment]
@alum300 Díky tohle je zatím asi nejrychlejší cesta. Já jsem ten MPD získával odchytáváním síťových požadavků přehrávače a v tom požadavku GET ten odkaz právě vypadá pouze takto:
https://ivys-vst19-5.o2tv.cz/atip/2ad57029ddd19ebed3167f969146e306/1682065546589/61924494878125885-pc.mpd?userId=2b47d32f-88b2-48a5-bcc5-fd4a78ae39c6

CTRL+SHIFT+i mi po dle fokusu a polohy myšítka ukazovalo a skrývalo (ve Firefoxu) vývojářské nástroje. Takže jsem pojal podezření, že to tu asi nefunguje úplně správně. Nakonec ale jo...

Pro případné další zájemce rychlý obrázkový návod:
![Stažení MPD](https://user-images.githubusercontent.com/131013927/233597667-cb774752-e4b3-487a-a3c1-9f4e3ce1a156.png)

@ibv Díky za příkladnou podporu, odkazy proštuduju. 👍  :)

Síťovku mám integrovanou na základní desce Gigabyte, tedy v mém případě:
Realtek PCIe GbE Family Controller
s ovladačem: Realtek 31.12.2020 (10.46.1231.2020 podepsaný Microsoft Windows Hardware Compatibility)



Už teď je ale leccos vidět v tom .MPD (ale teď znám o něco rychlejší způsob jak jej získat).

Ukázka .MPD nešifrovaný (Zemřít znovu):
[61924494878125885-pc.mpd.txt](https://github.com/ibv/YTD/files/11294311/61924494878125885-pc.mpd.txt)

Ukázka .MPD šifrovaný (Belphegor: Fantom Louvru):
[dwv-61924494878125631-pc.mpd.txt](https://github.com/ibv/YTD/files/11294321/dwv-61924494878125631-pc.mpd.txt)

Za povšimnutí stojí sekce ContentProtection a cenc:pssh, která obsahuje něco, co mi připomíná dešifrovací klíč (ale nemusí to tak být).

**Comment by ladis2000** [comment]
Opravená verze YTD 1.70.0.3 funguje.
Zkoušeno (jako vždy) na prvním dílu https://www.ceskatelevize.cz/porady/11118197787-volha/

**Comment by alum300** [comment]
@ibv Děkuji, oprava funguje v dřívějším rozsahu. Použito Realtek PCIe GBE Family Controller, ovladač 2013.
