### ISSUE TITLE
Změna na webu nova.cz

### ISSUE THREAD

**Issue by Jenikcz** [ibv/YTD#71]
Dobrý den,

Mohu požádat o úpravu stahování, webmaster změnil programování videí v archivu, po zadání videa do programu nezačne stahování.

Děkuji.

S pozdravem,

Jenikcz

**Comment by ibv** [comment]
Opraveno ve skriptech verze **1.70.20230810.0**,
aktualizovat obvyklým způsobem.

**Comment by Jerry007B** [comment]
Zdravím,

mám poslední verzi YTD (1.70) i skriptů (1.70.20230810.0), ale stahování z webu novy nefunguje, po vložení odkazu (např. https://tv.nova.cz/porad/masterchef-cesko/epizoda/377057-1-dil) je status pouze "Čeká se" nebo "Připravuje se download", ale stahování nikdy nezačne.

Dělám něco špatně já?

Díky za odpověď,
Jerry007B

**Comment by ibv** [comment]
Zdravím,
zkusil jsem odkaz a normálně jde stáhnout, MPEG-DASH stahování je nastaveno dle [odkazu](../issues/68),
úplně dole?

**Comment by Jerry007B** [comment]
> Zdravím, zkusil jsem odkaz a normálně jde stáhnout, MPEG-DASH stahování je nastaveno dle [odkazu](../issues/68), úplně dole?

Skvělé, po nastavení podle návodu už funguje jak má. Díky!

**Comment by PavelJCZ** [comment]
Ahoj, nenastala nějaká změna na nově? Doposud mi vše fungovalo a nyní se připravuje DL a nic nezačne. Napíše Chyba skriptu: Regulární výraz nebyl splněn.....

Díky Pavel

![ytd chyba](https://github.com/ibv/YTD/assets/149933364/73be14cf-f148-41ac-9a55-d6aa8469e3e8)

**Comment by ladis2000** [comment]
Potvrzuji úplně stejný problém. Dodnes vše fungovalo (1.70.20230810.0) a Nova nejde stahovat. Stejný problém, jako píše PavelJCZ.

**Comment by PavelJCZ** [comment]
Tak to bude manželka smutná. Líbilo se jí koukat na seriály bez reklam.

I tak velice děkuji za snahu.
P.

**Comment by Jerry007B** [comment]
Tak to se to brzo rozšíří všude. Např. ČT už taky má seriály zašifrované, po stažení je nelze přehrát. Včera jsem se snažil stáhnout StarDance.

**Comment by ibv** [comment]
Je v tom nějaká finta, ve FireFox nemám povolené DRM a přesto jde stream přehrát.
Pokud si pustím dev nástroje (F12), tak se dostanu k souborům .m3u8, ze kterých si potom můžu stream pomocí ffmpeg stáhnout a je normálně hratelný.

ffmpeg -i "https://nova-ott-v...........-.m3u8" -c copy -bsf:a aac_adtstoasc "output.mp4"


![o-015](https://github.com/ibv/YTD/assets/2648561/1545b2e0-e237-43f6-9739-464f556c4a40)

**Comment by PavelJCZ** [comment]
Půjde to tedy nějak "zprovoznit"? Bylo by určitě příjemnější to mít na klik v programu.

**Comment by Hagar82** [comment]
Aktuální Youtube-DLP stahuje z Novy:
[https://github.com/yt-dlp/yt-dlp-nightly-builds/releases](url)

Přehrávání taky není problém.
![01](https://github.com/ibv/YTD/assets/153420455/7a91a277-05af-4d38-9a4c-7a2eec871781)

**Comment by ibv** [comment]
Opraveno ve skriptech verze 1.70.20231212.0,
aktualizovat obvyklým způsobem.
Funguje pro zpravodajství,.. v sekci /videa.
