### ISSUE TITLE
Podpora 4k rozlišení

### ISSUE THREAD

**Issue by Hagar82** [ibv/YTD#74]
Bylo by prosím možné přidat podporu pro 4k rozlišení?
Při vysokém rozlišení je program opravdu špatně použitelný.
![Clipboard_12-12-2023_01](https://github.com/ibv/YTD/assets/153420455/10f6c6f0-c9a2-41eb-a555-f56fd795dc61)

**Comment by ibv** [comment]
Zkuste verzi 1.7.0.4 v sekci release, soubor [ytd-64-scaled.7z](https://github.com/ibv/YTD/releases/download/v1.70/ytd-64-scaled.7z)
Nemám to kde vyzkoušet, nedisponuji takovým rozlišením monitoru.

**Comment by Hagar82** [comment]
Vůbec mi to nechce povolit stáhnout, prý je to zavirované ):
![01](https://github.com/ibv/YTD/assets/153420455/4d2bdc04-d4bf-40f5-8cdb-3e344d7502b3)

**Comment by ibv** [comment]
Tak ještě vydržte, prověřím, jestli jsem nějakého neřáda nechytil.

**Comment by ibv** [comment]
Jsem to zkoušel Eset Endpointem i onlinescannerem a nic mi to nehlásí, tak nevim.

**Comment by Hagar82** [comment]
Tak jsem to zkusil znovu, antivir už nic nenamítal, spustilo se, vypadá to lépe, jenom ty ikonky by to ještě chtělo zvětšit.
Hlavním problémem je, že to nestahuje ):

**Comment by ibv** [comment]
Zkusit ještě aktualizovat skripty podle navodu [zde](https://github.com/ibv/YTD/issues/5) .

![o-72](https://github.com/ibv/YTD/assets/2648561/8442ba9a-0c67-477d-999b-95ef4b50d5b1)

![o-73](https://github.com/ibv/YTD/assets/2648561/93b1ec32-847a-499a-a0f3-b871a2658b7d)
