### ISSUE TITLE
Česká bedna KO

### ISSUE THREAD

**Issue by MyloshB** [ibv/YTD#77]
Milý dobrodiňče, pane Ivoši (IBV). 
Moc se Vám omlouvám za tak špatnou zprávu zrovna před víkendem, ale je to bohužel tak...
Kazišuci z Fialovy bedny zase zaškodili a YTD nefachčí tak, jak je zvykem.
Zde jsou 2 příklady pořadů, které ještě minulý týden byly v YTD OK a dnes jsou polámané: 
https://www.ceskatelevize.cz/porady/1093836883-na-plovarne/224542152000009
https://www.ceskatelevize.cz/porady/16047276686-vyborna-show/224544160330003
Děkuji Vám již předem za laskavost, stále držím palce a zdravím, Mylosh B.

**Comment by ibv** [comment]
Zdravím, uvedené odkazy nejsou "pokažené", jsou pouze zašifrované proti kopírování/přehrávání pomocí DRM.

![o-69](https://github.com/ibv/YTD/assets/2648561/40bec6ff-b0c0-44a1-b5eb-3d6df532a8f0)

**Comment by MyloshB** [comment]
Děkuji za odpověď, kterou si vykládám tak, že stávající YTD neumí stáhnout uvedená videa ve sledovatelném formátu.
Tím pádem bych se Vás rád zeptal:
a) Byl byste ochoten naprogramovat YTD tak, aby to šlo? Samozřejmě chápu, že jde především o Váš čas, analýzu možností, možná i nákup nějaké placené komponenty na dešifrování DRM, spoustu programování atd. Tím pádem by vznikla placená verze YTD. To mi ale vůbec nevadí, cenu akceptuji, ať už bude jednorázová či formou ročního předplatného.
b) Pokud byste do toho nešel, poradíte mi, prosím, cokoliv, čím půjdou uvedené odkazy stáhnout? Je mi jedno, jestli to bude SW zadax nebo za pár tyček :-)
Děkuji Vám již předem za odpověď, MB.

**Comment by ibv** [comment]
Zdravím, neplánuji rozšiřovat funkčnost YTD tímto směrem, na webu existují nástroje, které umí "opravit" nefungující videa.  Zkoušel jsem několik návodů z webu a cesta k výsledku je poměrně trnitá, ale nakonec jsem uspěl.
Ta správná klíčová slova jsou "mp4decrypt", "wks-keys", "wvdumper/dumper","frida-server"

[https://forum.videohelp.com/threads/404994-Decryption-and-the-Temple-of-Doom](https://forum.videohelp.com/threads/404994-Decryption-and-the-Temple-of-Doom)
[https://www.ismailzai.com/blog/picking-the-widevine-locks](https://www.ismailzai.com/blog/picking-the-widevine-locks)
[https://forum.root.cz/index.php?topic=25636.30](https://forum.root.cz/index.php?topic=25636.30)

![o-014](https://github.com/ibv/YTD/assets/2648561/d121e5e3-4755-433a-8c4c-1bf2b014b54d)
