### ISSUE TITLE
Problém s YT

### ISSUE THREAD

**Issue by MyloshB** [ibv/YTD#78]
Zdravím a hlásím problém se stahováním přímo z YT.
Zkoušel jsem v YTD všechny možné kombinace nastavení stahovače pro server www.youtube.com, ale nic mi nepomohlo.
Tak se holt musím obrátit na autora s dotazem, co je špatně ;-)
Pokouším se stáhnout tyto 2 videa:
--> https://www.youtube.com/watch?v=GJlqhznmFTY
--> https://www.youtube.com/watch?v=o8hkMfs82cU
YTD hlásí chybu _Proměnná "Format-URL Map" nebyla nalezena (EDownloadThreadError)_
Děkuji již předem za radu, MB.

**Comment by ibv** [comment]
Zkuste to stahovat pomocí [https://github.com/yt-dlp/yt-dlp/releases](https://github.com/yt-dlp/yt-dlp/releases),
má to více možností nastavení kvality, rozlišení ,...
