### ISSUE TITLE
Problém se stahováním z České televize

### ISSUE THREAD

**Issue by hawkinsjim** [ibv/YTD#79]
Dobrý den,

chtěl jsem stáhnout z ČT2 pořad https://www.ceskatelevize.cz/porady/15819351688-velka-vlakova-loupez/224381490340001/.  Program zůstal ve stavu "Čeká se" a nestahuje. Mám verzi 1.70.20240323.0. Podívejte se na to, prosím.

Zdraví

Petr Linhart

**Comment by ibv** [comment]
Zdravím, múžete to prosím zkusit i na nějakém jiném počítači? 
Prubnul jsem stahování ve Windows i na Linuxu a stahování normálně jede.

![o-70](https://github.com/ibv/YTD/assets/2648561/f6664bca-b288-4dbd-83ba-bd9a57209032)

**Comment by hawkinsjim** [comment]
Zkusil jsem to celkem na 3 počítačích s Windows 10, Linux nemám a všechno stejné. Nastavení MPEG-DASH jsem našel, zaškrtl a stejné.  HLS nevím kde nastavit. Na jednom počítači jsem ytd dal explicitně do firewallu a také nic. Naposledy jsem stahoval 1. 5. 2024 15:40 a šlo to.  Mám kabelový internet od Vodafonu. 
Dá se nějak zjistit, na co stahování čeká?

**Comment by hawkinsjim** [comment]
Ještě dodávám, že u řádku stahovače MPEG-DASH mám zaškrtnuty obě položky: video i audio stream. U stahovače Česká televize je jen jedna položka.
Také jsem zjistil, že lze stáhnout jen 1 url. Pokud po skončení stahování zadám další, program zůstane ve stavu Čeká. Musím všechno ukončit, odhlásit se a znovu přihlásit. Pak mám zase jeden pokus.

**Comment by hawkinsjim** [comment]
Tak všechno je jinak. Všiml jsem si, že na webu máte novější verzi. Sice jen o několik dní, ale stáhl jsem ji. Je v angličtině a vypisuje se tam OpenSSL verze 3.1.0 14. MAR 2023.
Nastavil jsem všude mpeg-dash a stáhl mpd adresu. Opět se stáhl jen soubor video.mpv. Pak jsem u stahovače Česká televize odškrtl mpeg-dash a zadal jsem adresu videa z příkazového řádku. V pořádku se stáhlo. Bez restartu jsem stáhl ještě jedno video.
Znamená to, že téměř vše funguje i u mne. 
Zbývá stahování přes mpeg-dash z České televize. Nestahuje se zvuk. Je tam jen jedno zaškrtávací pole, možná jej program interpretuje jako video a audio zůstává nenastavené.  Až budete mít chvilku, mrkněte an to, prosím.

**Comment by ibv** [comment]
Zdravím, zkusil jsem dotáhnout uváděný odkaz a video i audio stream byl korektně stažen.
Všiml jsem si, že zkoušíte stahovat mpd manifest, u CT jde stahovat přímo z odkazu, mpd manifest si YTD vyzobe sám. Pokud v nastavení downloaderů u CT odškrtnete MPEG-DASH, stahuje se TS (HLS) stream, obsahuje video i audio v jednom souboru, jeden checkbox u volby CT/MPEG je v pořádku, aplikuje se na video i audio současně. 
Současné stahování několika streamů funguje, uváděný problém se mi nepodařilo nasimulovat.

**Comment by hawkinsjim** [comment]
Vyzkoušel jsem a funguje mi to, jak popisujete. Děkuji za pomoc.

Zdraví

Petr Linhart
